%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%   
%   Release 1.0 : January 2019
%
%   Routine EcritNetList2D called by Compute.m
%
%   Function: Write the input file (e.g.: xx.sp, xx.cir) for the Spice Simulator 
%
%   Remarks:
%   tlm.result(numeroduptincident)={numduptcible1, trgdroite1, trggauche1, R1, C1, R2, C2, h ...}
%   with h=1 : If the segment is in the outer electrodes and one edge is in contact with the organic medium (serum) 
%          2 : If the segment is in the organic medium and one edge is in contact with the outer electrodes 
%          3 : If the segment is in the cytoplasm(1) and one edge is in contact with the organic medium (serum) 
%          4 : If the segment is in the organic medium and one edge is in contact with the cytoplasm(1) 
%          5 : If the segment is in the cytoplasm(1) and one edge is in contact with the nucleus(1) 
%          6 : If the segment is in the nucleus(1) and one edge is in contact with the cytoplasm(1)
%          7 : If the segment is in the cytoplasm(1) and one edge is in contact with the mitochon(1) 
%          8 : If the segment is in the mitochon(1) and one edge is in contact with the cytoplasm(1)
%          9 : If the segment is in the cytoplasm(2) and one edge is in contact with the organic medium
%         10 : If the segment is in the organic medium and one edge is in contact with the cytoplasm(2) 
%         11 : If the segment is in the cytoplasm(2) and one edge is in contact with the nucleus(2) 
%         12 : If the segment is in the nucleus(2) and one edge is in contact with the cytoplasm(2)
%         13 : If the segment is in the cytoplasm(2) and one edge is in contact with the mitochon(2) 
%         14 : If the segment is in the mitochon(2) and one edge is in contact with the cytoplasm(2)
%          Length of the segment : If the segment is at the interface (for parasitics with ST2)
%
%   tlm.geom.boundaryEE{numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   outer electrodes - organic medium (serum) (for the parasitics with ST1)
%                                   see subroutine CalculRC2D.m
%   tlm.geom.boundaryEC{numcell,numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   cytoplasm(1) or (2) - organic medium (serum)
%                                   see subroutine CalculRC2D.m
%   tlm.geom.boundaryEN{numcell,numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   nucleus(1) or (2) - cytoplasm (1) or (2)
%                                   see subroutine CalculRC2D.m
%   tlm.geom.boundaryEM{numcell,numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   mitochondria(1) or (2) - cytoplasm(1) or (2)
%                                   see subroutine CalculRC2D.m
%
%   tlm.geom.airvol(numdutrg)= third of the surface of the triangle
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm,model]=EcriNetList2D(tlm,model)
%function [tlm,fem]=EcriNetList2D(tlm,fem)

%Initialization

global fem_mesh_p;
global fem_mesh_t;
global fem_mesh_e;
    
tlm.conf.Resistor=0;
tlm.conf.Capacitor=0;
    
name1=sprintf('%s.cir',tlm.conf.Name);        % Name of the file for the Net List
fid=fopen(name1, 'w');                     % Open the File

name2=sprintf('%s.cor',tlm.conf.Name);        % Name of the file for the coordinates of each node
fie=fopen(name2, 'w');                     % Open the File
%name3=sprintf('%s.tri',tlm.conf.Name);        % Name of the file for the listing of the nodes numbers of each triangle
%fif=fopen(name3, 'w');                     % Open the File

fprintf(fid, '%s.cir\n',tlm.conf.Name);            % Write the first line of the file which is use as a title of the graphical output
fprintf(fid, '********************************************************************************\n');            
fprintf(fid, '*\n');            
fprintf(fid, '*                        Spice Netlist Generated by\n'); 
fprintf(fid, '*\n');            
fprintf(fid, '*                              BIOCAD Program\n');            
fprintf(fid, '*                               Release 1.0\n');            
fprintf(fid, '*\n');            
fprintf(fid, '*   Authors: Vincent Senez\n'); 
fprintf(fid, '*\n');            
fprintf(fid, '*   Release 1.0 : January 2019\n');     
fprintf(fid, '*\n');            
fprintf(fid, '********************************************************************************\n');            

% Define the type of analysis

fprintf(fid,'.CONTROL \n');                         %SPICE3 format allow complex simulation using conditions
fprintf(fid,'  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC %f %f %f \n',tlm.var.frequence.step,tlm.var.frequence.min,tlm.var.frequence.max);                        % Wide spectrum analysis, logarithmic variation between 1 and 1e10 Hz, 25 points per decade
if tlm.conf.points==1       % 2 points measurements 
    fprintf(fid, '  WRITE %s.spi vdb(%u,%u)-vdb(%u)-100 vp(%u,%u)-vp(%u) \n', ...
            tlm.conf.Name,tlm.ind.pt.elec1,tlm.ind.pt.elec2,tlm.ind.pt.elec2,tlm.ind.pt.elec1,tlm.ind.pt.elec2,tlm.ind.pt.elec2);
elseif tlm.conf.points==2       % 2 points measurements 
    fprintf(fid, '  WRITE %s.spi vdb(%u,%u)-vdb(%u)-100 vp(%u,%u)-vp(%u) \n', ...
            tlm.conf.Name,tlm.ind.pt.elec1,tlm.ind.pt.elec2,tlm.ind.pt.elec2,tlm.ind.pt.elec1,tlm.ind.pt.elec2,tlm.ind.pt.elec2);
elseif tlm.conf.points==4
%    fprintf(fid, '  WRITE %s.spi db(v(%u)) ph(v(%u)) db(v(%u)) ph(v(%u)) db(v(%u)) ph(v(%u)) \n', ...
    fprintf(fid, '  WRITE %s.spi vdb(%u,%u)-vdb(%u)-100 vp(%u,%u)-vp(%u) \n', ...
            tlm.conf.Name,tlm.ind.pt.mesu1,tlm.ind.pt.mesu2,tlm.ind.pt.elec2,tlm.ind.pt.mesu1,tlm.ind.pt.mesu2,tlm.ind.pt.elec2);
    fprintf(fid, '  PLOT VDB(%u,%u)-VDB(%u)-100 \n', ...                              % .PLOT generates the .cou file for exploitation of the results by Xelga                             
            tlm.ind.pt.mesu2, tlm.ind.pt.mesu1, tlm.ind.pt.elec1);                                                 
end
fprintf(fid,'  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC 1 %f %f \n',tlm.var.frequence.min,tlm.var.frequence.min);                        % Wide spectrum analysis, logarithmic variation between 1 and 1e10 Hz, 25 points per decade
fprintf(fid, '  WRITE %s.spi_cou all \n',[tlm.conf.Name '_' num2str(tlm.var.frequence.min) 'Hz']);
fprintf(fid,'  DESTROY ALL \n'); 
ex=round((log10(tlm.var.frequence.max)-log10(tlm.var.frequence.min))/2);
if tlm.var.frequence.max==10
    ex=0;
end
f=5*10^ex;
fprintf(fid, '  AC DEC 1 %f %f \n',f,f);                        % Wide spectrum analysis, logarithmic variation between 1 and 1e10 Hz, 25 points per decade
fprintf(fid, '  WRITE %s.spi_cou all \n',[tlm.conf.Name '_' num2str(f) 'Hz']);
fprintf(fid,'  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC 1 %f %f \n',tlm.var.frequence.max,tlm.var.frequence.max);                        % Wide spectrum analysis, logarithmic variation between 1 and 1e10 Hz, 25 points per decade
fprintf(fid, '  WRITE %s.spi_cou all \n',[tlm.conf.Name '_' num2str(tlm.var.frequence.max) 'Hz']);
fprintf(fid,'.ENDC \n');

fprintf(fid, 'Vin\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1,tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
fprintf(fid, 'Rg\t%u\t0\t7e-5\n',tlm.ind.pt.elec2);                % Right outer electrode where there is the ground 
%fprintf(fid, 'Cs1\t%u\t%u\t1e-8\n',tlm.ind.pt.elec2,tlm.ind.pt.mesu2);                 
%fprintf(fid, 'Cs2\t%u\t%u\t1e-8\n',tlm.ind.pt.elec1,tlm.ind.pt.mesu1);
%fprintf(fid, 'Ram\t%u\t%u\t1e2\n',tlm.ind.pt.mesu1,tlm.ind.pt.mesu2);
%fprintf(fid, 'Ca1\t%u\t0\t1e-8\n',tlm.ind.pt.mesu2);                 
%fprintf(fid, 'Ca2\t%u\t0\t1e-8\n',tlm.ind.pt.mesu1);
if abs(tlm.var.EpaisseurChambre-tlm.var.EpaisseurElectrode)<1e-10 
    fprintf(fid, 'Vin1\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1sup(1),tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
    fprintf(fid, 'Vin2\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1sup(2),tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
    fprintf(fid, 'Vin3\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1sup(3),tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
    fprintf(fid, 'Vin4\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1sup(4),tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
    fprintf(fid, 'Vin5\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1sup(5),tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
    fprintf(fid, 'Vin6\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec1sup(6),tlm.var.v0);        % Left outer electrode where there is the solicitation (here tlm.var.v0)
    fprintf(fid, 'Rg1\t%u\t0\t7e-5\n',tlm.ind.pt.elec2sup(1));                % Right outer electrode where there is the ground 
    fprintf(fid, 'Rg2\t%u\t0\t7e-5\n',tlm.ind.pt.elec2sup(2));                % Right outer electrode where there is the ground 
    fprintf(fid, 'Rg3\t%u\t0\t7e-5\n',tlm.ind.pt.elec2sup(3));                % Right outer electrode where there is the ground 
    fprintf(fid, 'Rg4\t%u\t0\t7e-5\n',tlm.ind.pt.elec2sup(4));                % Right outer electrode where there is the ground 
    fprintf(fid, 'Rg5\t%u\t0\t7e-5\n',tlm.ind.pt.elec2sup(5));                % Right outer electrode where there is the ground 
    fprintf(fid, 'Rg6\t%u\t0\t7e-5\n',tlm.ind.pt.elec2sup(6));                % Right outer electrode where there is the ground 
end

%Write the value of all electrical components in the .cir file

    for i=1:1:size(fem_mesh_p,2)                                        % Loop on the nodes
%        if i==47
%            disp(i);
%        end
       fprintf(fie, '%u\t%e\t%e\t%e\n', i, fem_mesh_p(1,i), fem_mesh_p(2,i), 0);     % Save the coordinates of the mesh in xxx.cor    

       if size(tlm.result{i},2)~=0                                     % if the array for node i is filled in (node i has been selected as incident)
            for j=8:8:size(tlm.result{i},2)
                if tlm.result{i}{j-5}==0                                % If we are on the edge of the simulation domain
%                     fprintf(fif, '%u\t0\t%u\t%u\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7});
                     if (size(tlm.geom.boundaryEE{i},2)~=1 && size(tlm.geom.boundaryEE{tlm.result{i}{j-7}},2)~=1) % The nodes i and tlm.result{i}{j-7} is not on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_0\t%u\t%u\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});        % the name of the resistor is R_triangledroit_0, it is set between nodes i and numduptcible1
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_0\t%u\t%u\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});    % the name of the capacitor is C_triangledroit_0, it is set between nodes i and numduptcible1
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                     elseif (size(tlm.geom.boundaryEE{i},2)==1) % The node i is on the boundary
                        if (tlm.result{i}{j}==1) % The segment is in the right or left outer electrode
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_0\t%ubis\t%u\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});        % the name of the resistor is R_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_0\t%ubis\t%u\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});    % the name of the capacitor is C_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        elseif (tlm.result{i}{j}==2) % The segment is in the organic medium
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_0\t%uter\t%u\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});        % the name of the resistor is R_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_0\t%uter\t%u\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});    % the name of the capacitor is C_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                     elseif (size(tlm.geom.boundaryEE{tlm.result{i}{j-7}},2)==1) % The node tlm.result{i}{j-7} is on the boundary
                        if (tlm.result{i}{j}==1) % The segment is in the right or left outer electrode
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_0\t%u\t%ubis\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});        % the name of the resistor is R_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_0\t%u\t%ubis\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});    % the name of the capacitor is C_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        elseif (tlm.result{i}{j}==2) % The segment is in the organic medium
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_0\t%u\t%uter\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});        % the name of the resistor is R_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_0\t%u\t%uter\t%17.16e\n', tlm.result{i}{j-6}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});    % the name of the capacitor is C_triangledroit_0, it is set between nodes i and numduptcible1
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                     end
                else                                                    % If we are not on the edge of the simulation domain
                    if (tlm.result{i}{j}==0)                            % If we are not close to interfaces where special boundary conditions should be setup (excitation electrodes, membranes)
%                        fprintf(fif, '%u\t%u\t%u\t%u\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7});
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, ...
                                    tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, ...
                                    tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    elseif (tlm.result{i}{j}==1)    % The segment {i,j} is in the left or right outer electrodes
                        if (size(tlm.geom.boundaryEE{i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%ubis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, ...
                                        i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%ubis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, ...
                                        i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%ubis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, ...
                                        i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%ubis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, ...
                                        i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==2)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the left or right outer electrodes
                        if (size(tlm.geom.boundaryEE{i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%uter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%uter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%uter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%uter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==3)    % The segment {i,j} is in the cytoplasm(1) and i or j is on the boundary with the organic medium
                        if (size(tlm.geom.boundaryEC{1,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%umbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%umbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else   % the node tlm.result{i}{j-7} is on the boundary               
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==4)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the cytoplasm(1)
                        if (size(tlm.geom.boundaryEC{1,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%umter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%umter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else  % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==5)    % The segment {i,j} is in the cytoplasm(1) and i or j is on the boundary with the nucleus(1)
                        if (size(tlm.geom.boundaryEN{1,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%unbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%unbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else    % the node tlm.result{i}{j-7} is on the boundary              
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==6)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the nucleus(1)
                        if (size(tlm.geom.boundaryEN{1,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%unter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%unter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else  % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==7)    % The segment {i,j} is in the cytoplasm(1) and i or j is on the boundary with the mitochon(1)
                        if (size(tlm.geom.boundaryEM{1,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%uobis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%uobis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else    % the node tlm.result{i}{j-7} is on the boundary              
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==8)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the mitochon(1)
                        if (size(tlm.geom.boundaryEM{1,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%uoter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%uoter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else  % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==9)    % The segment {i,j} is in the cytoplasm(2) and i or j is on the boundary with the organic medium
                        if (size(tlm.geom.boundaryEC{2,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%umbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%umbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else   % the node tlm.result{i}{j-7} is on the boundary               
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==10)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the cytoplasm(2)
              
                        if (size(tlm.geom.boundaryEC{2,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%umter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%umter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else  % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==11)    % The segment {i,j} is in the cytoplasm(2) and i or j is on the boundary with the nucleus(2)
                        if (size(tlm.geom.boundaryEN{2,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%unbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%unbis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else    % the node tlm.result{i}{j-7} is on the boundary              
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==12)    % The segment {i,j} is in the nucleus(2) and i or j is on the boundary with the cytoplasme(2)
                        if (size(tlm.geom.boundaryEN{2,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%unter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%unter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else  % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==13)    % The segment {i,j} is in the cytoplasm(2) and i or j is on the boundary with the mitochon(2)
                        if (size(tlm.geom.boundaryEM{2,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%uobis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%uobis\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else    % the node tlm.result{i}{j-7} is on the boundary              
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i, tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (tlm.result{i}{j}==14)    % The segment {i,j} is in the mitochon(2) and i or j is on the boundary with the cytoplasme(2)
                        if (size(tlm.geom.boundaryEM{2,i},2)==1) % The node i is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%uoter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%uoter\t%u\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        else  % the node tlm.result{i}{j-7} is on the boundary
                            if tlm.result{i}{j-4}~=-1
                                fprintf(fid, 'R%u_%u\t%u\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                tlm.conf.Resistor=tlm.conf.Resistor+1;
                            end
                            if tlm.result{i}{j-3}~=0
                                fprintf(fid, 'C%u_%u\t%u\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                            end
                        end
                    elseif (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.elec1)||...            % Here we are exactly on the special boundary (solicitation electrode)
                           (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.elec1)||...
                           (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.elec2)||...
                           (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.elec2)
                           % Impedance in the organic medium
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Rter%u_%u\t%uter\t%uter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Cter%u_%u\t%uter\t%uter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                           % Impedance in the solicitation electrode
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Rbis%u_%u\t%ubis\t%ubis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cbis%u_%u\t%ubis\t%ubis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    elseif ((fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Cytoplasme(1))&&...     % Here we are exactly on the special boundary (cell membrane)
                            (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.MilOrga))||...                 
                            ((fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Cytoplasme(1))&&...
                            (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.MilOrga))
                            % Impedance in the organic medium
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Rmter%u_%u\t%umter\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Cmter%u_%u\t%umter\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                            % Impedance in the Cytoplasme
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Rmbis%u_%u\t%umbis\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cmbis%u_%u\t%umbis\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    elseif ((fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Cytoplasme(2))&&...     % Here we are exactly on the special boundary (cell membrane)
                            (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.MilOrga))||...                 
                            ((fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Cytoplasme(2))&&...
                            (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.MilOrga))
                            % Impedance in the organic medium
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Rmter%u_%u\t%umter\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Cmter%u_%u\t%umter\t%umter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                            % Impedance in the Cytoplasme
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Rmbis%u_%u\t%umbis\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cmbis%u_%u\t%umbis\t%umbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    elseif ((fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Cytoplasme(1))&&...     % Here we are exactly on the special boundary (Nucleus membrane)
                            (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Nucleus(1)))||...                 
                            ((fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Cytoplasme(1))&&...
                            (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Nucleus(1)))    
                            % Impedance in the nucleus
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Rnter%u_%u\t%unter\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Cnter%u_%u\t%unter\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                            % Impedance in the Cytoplasme
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Rnbis%u_%u\t%unbis\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cnbis%u_%u\t%unbis\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    elseif ((fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Cytoplasme(2))&&...     % Here we are exactly on the special boundary (Nucleus membrane)
                            (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Nucleus(2)))||...                 
                            ((fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Cytoplasme(2))&&...
                            (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Nucleus(2)))    
                            % Impedance in the nucleus
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Rnter%u_%u\t%unter\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Cnter%u_%u\t%unter\t%unter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                            % Impedance in the Cytoplasme
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Rnbis%u_%u\t%unbis\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cnbis%u_%u\t%unbis\t%unbis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    elseif ((fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Cytoplasme(1))&&...     % Here we are exactly on the special boundary (Nucleus membrane)
                            (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Mitocho(1)))||...                 
                            ((fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Cytoplasme(1))&&...
                            (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Mitocho(1)))    
                            % Impedance in the mitochondria
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Roter%u_%u\t%uoter\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Coter%u_%u\t%uoter\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                            % Impedance in the Cytoplasme
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Robis%u_%u\t%uobis\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cobis%u_%u\t%uobis\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    elseif ((fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Cytoplasme(2))&&...     % Here we are exactly on the special boundary (Nucleus membrane)
                            (fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Mitocho(2)))||...                 
                            ((fem_mesh_t(tlm.result{i}{j-6},1)==tlm.ind.dom.Cytoplasme(2))&&...
                            (fem_mesh_t(tlm.result{i}{j-5},1)==tlm.ind.dom.Mitocho(2)))    
                            % Impedance in the mitochondria
                                if tlm.result{i}{j-4}~=-1
                                    fprintf(fid, 'Roter%u_%u\t%uoter\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-4});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-3}~=0
                                    fprintf(fid, 'Coter%u_%u\t%uoter\t%uoter\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-3});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                            % Impedance in the Cytoplasme
                                if tlm.result{i}{j-2}~=-1
                                    fprintf(fid, 'Robis%u_%u\t%uobis\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-2});
                                    tlm.conf.Resistor=tlm.conf.Resistor+1;
                                end
                                if tlm.result{i}{j-1}~=0
                                    fprintf(fid, 'Cobis%u_%u\t%uobis\t%uobis\t%17.16e\n', tlm.result{i}{j-6}, tlm.result{i}{j-5}, i ,tlm.result{i}{j-7}, tlm.result{i}{j-1});
                                    tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                                end
                    end %if (tlm.result{i}{j}==0)
                end %if tlm.result{i}{j-5}==0
            end %for j
        end %if size(tlm.result{i},2)~=0
    
% Ajout des éléments parasites

        if (size(tlm.geom.boundaryEE{i},1)==1)                   %parasite of the outer electrode (Ci in parallel with (Rt + Rw // Cw); (node i is on the boundary)
            fprintf(fid,'Ci%u\t%ubis\t%uter\t%17.16e\n',i,i,i,tlm.var.Ci*tlm.geom.boundaryEE{i});
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            fprintf(fid,'Rw%u\t%uquad\t%uter\tR={%17.16e/sqrt(FREQ)}\n',i,i,i,tlm.var.Rwf/tlm.geom.boundaryEE{i});
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cw%u\t%uquad\t%uter\tC={%17.16e*sqrt(FREQ)}\n',i,i,i,tlm.var.Cwf*tlm.geom.boundaryEE{i});
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            fprintf(fid,'Rt%u\t%ubis\t%uquad\t%17.16e\n',i,i,i,tlm.var.Rt/tlm.geom.boundaryEE{i});
            tlm.conf.Resistor=tlm.conf.Resistor+1;        
        elseif (size(tlm.geom.boundaryEC{1,i},1)==1)               %cell membrane model (node i is on the boundary)
            if tlm.var.sig.MembCel(1)~=0
                fprintf(fid,'Rm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurMembrane/(tlm.var.sig.MembCel(1)*tlm.geom.boundaryEC{1,i}))/2);
                tlm.conf.Resistor=tlm.conf.Resistor+1;
            end
            if tlm.var.eps.MembCel(1)~=0
                fprintf(fid,'Cm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,((tlm.var.eps.MembCel(1)*tlm.geom.boundaryEC{1,i})/tlm.var.EpaisseurMembrane)*2);
                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            end
            
        elseif (size(tlm.geom.boundaryEC{2,i},1)==1)               %cell membrane model (node i is on the boundary)
            if tlm.var.sig.MembCel(1)~=0
                fprintf(fid,'Rm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurMembrane/(tlm.var.sig.MembCel(2)*tlm.geom.boundaryEC{2,i}))/2);
                tlm.conf.Resistor=tlm.conf.Resistor+1;
            end
            if tlm.var.eps.MembCel(1)~=0
                fprintf(fid,'Cm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,((tlm.var.eps.MembCel(2)*tlm.geom.boundaryEC{2,i})/tlm.var.EpaisseurMembrane)*2);
                tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            end
        
        elseif (size(tlm.geom.boundaryEN{1,i},1)==1)               %nucleus membrane model (node i is on the boundary)
            fprintf(fid,'Rn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurNucleus/(tlm.var.sig.MembNuc(1)*tlm.geom.boundaryEN{1,i}))/2);
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,((tlm.var.eps.MembNuc(1)*tlm.geom.boundaryEN{1,i})/tlm.var.EpaisseurNucleus)*2);
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;            
        elseif (size(tlm.geom.boundaryEN{2,i},1)==1)               %nucleus membrane model (node i is on the boundary)
            fprintf(fid,'Rn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurNucleus/(tlm.var.sig.MembNuc(2)*tlm.geom.boundaryEN{2,i}))/2);
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,((tlm.var.eps.MembNuc(2)*tlm.geom.boundaryEN{2,i})/tlm.var.EpaisseurNucleus)*2);
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;            
        elseif (size(tlm.geom.boundaryEM{1,i},1)==1)               %mitochondria membrane model (node i is on the boundary)
            fprintf(fid,'Ro%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurMitochon/(tlm.var.sig.MembMit(1)*tlm.geom.boundaryEM{1,i}))/2);
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Co%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,((tlm.var.eps.MembMit(1)*tlm.geom.boundaryEM{1,i})/tlm.var.EpaisseurMitochon)*2);
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;                        
        elseif (size(tlm.geom.boundaryEM{2,i},1)==1)               %mitochondria membrane model (node i is on the boundary)
            fprintf(fid,'Ro%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurMitochon/(tlm.var.sig.MembMit(2)*tlm.geom.boundaryEM{2,i}))/2);
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Co%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,((tlm.var.eps.MembMit(2)*tlm.geom.boundaryEM{2,i})/tlm.var.EpaisseurMitochon)*2);
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;            
        end   
    end %for i

    fprintf(fid, '.END\n');
    fclose(fid);

    fclose(fie);

%fclose(fif);