%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%
%   Release 1.0 : January 2019
%
%   Function : Compute the various analysis
%
%   Called by : Biocad
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm,model]=Compute(tlm,fil, model)
    % Fonction principale de calcul de BIOCAD.
    % Entrées :
    %   - tlm : structure de configuration et variables du modèle TLM
    %   - fil : identifiant de fichier pour le log (si log activé)
    %   - model : objet COMSOL (LiveLink) avec la géométrie et le maillage
    % Sorties :
    %   - tlm : structure mise à jour (temps, stats, etc.)
    %   - model : éventuellement modifié par les fonctions appelées

    % Clear command window
    clc;  % Efface la fenêtre de commande MATLAB pour repartir proprement.

    % Close all figure windows
    if tlm.conf.fig>0  % Si des figures ont été ouvertes précédemment (compteur > 0)
        for i=tlm.conf.fig-1:-1:1  % Boucle à l’envers sur les numéros de figures existantes
            figure(i);             % Active la figure numéro i
            close(i);              % Ferme cette figure
        end
        tlm.conf.fig=0;  % Réinitialise le compteur de figures à 0
    end

    % Dock figures in Matlab GUI
    set(0,'DefaultFigureWindowStyle', 'normal') % Définit le mode d’ouverture des figures ('normal' = fenêtres séparées)

    % Print on the Command Window of Matlab
    Message=sprintf('\n ******* Start the Simulation');  % Prépare le message de début
    disp(Message);  % L’affiche dans la console

    % Initialization
    clear global fem_mesh_p;
    clear global fem_mesh_t;
    clear global fem_mesh_e;
    % On efface d'éventuelles anciennes valeurs des variables globales liées au maillage

    global fem_mesh_p;
    global fem_mesh_t;
    global fem_mesh_e;
    % On redéclare ces variables comme globales pour les utiliser dans d'autres fonctions

    % Open log file
    if tlm.conf.log==1  % Si l’option de log est activée

        % En-tête du fichier log
        fprintf(fil, '********************************************************************************\n');            
        fprintf(fil, '*\n');            
        fprintf(fil, '*                           Log File Generated by\n'); 
        fprintf(fil, '*\n');            
        fprintf(fil, '*                              BIOCAD Program\n');            
        fprintf(fil, '*                               Release 1.0\n');            
        fprintf(fil, '*\n');            
        fprintf(fil, '*   Authors: Vincent Senez\n'); 
        fprintf(fil, '*\n');            
        fprintf(fil, '*   Release 1.0 : January 2019\n');     
        fprintf(fil, '*\n');            
        fprintf(fil, '********************************************************************************\n');            
        fprintf(fil, '\n');            

        % Date and Time
        a=clock;  % Renvoie [année mois jour heure minute seconde]
        fprintf(fil,'\n Date: %u - %u - %u, Time: %u:%u:%u',fix(a(3)),fix(a(2)),fix(a(1)),fix(a(4)),fix(a(5)),fix(a(6)));
        % Écrit la date (jour-mois-année) et l’heure dans le log
        fprintf(fil,'\n ');

        fprintf(fil,'\n Files are saved in directory: ');
        fprintf(fil,'\n\t ''%s''', strcat(tlm.conf.store, "\", tlm.conf.Name));
        % Indique dans quel dossier les fichiers de résultats seront stockés

        fprintf(fil,'\n ');

        fprintf(fil,'\n The parameters of the analysis are:');
        % Introduction de la section décrivant les paramètres de la simulation

        % Write values of all Parameters in log file
        WritePara(tlm,fil);  % Fonction qui écrit dans le log toutes les valeurs de paramètres (contenues dans tlm)
    end

    if tlm.conf.log==1
        fprintf(fil,'\n ******* Start the Simulation');
        fprintf(fil,'\n ');
        % Répète dans le log le message de début de simulation
    end

    Message=sprintf('\n Files are saved in directory: ''%s''', strcat(tlm.conf.store, "\", tlm.conf.Name));
    disp(Message);  % Affiche dans la console le répertoire des fichiers de sortie

    % Drawing of the geometry
    Message=sprintf('\n Draw the Geometry with COMSOL MULTIPHYSICS routines');
    disp(Message);  % Message indiquant qu’on va manipuler la géométrie / le maillage COMSOL

    if tlm.conf.log==1
        fprintf(fil,'\n Draw the Geometry with COMSOL MULTIPHYSICS routines');
        fprintf(fil,'\n ');
        % Même info copiée dans le log
    end

    %Draw the structure
    tic;  % Démarre un chronomètre pour mesurer le temps de la partie "géométrie / maillage"

    if (tlm.conf.dim==2)  % Cas 2D
        % [tlm,model]=Geom2Dcad(tlm);  % Ancienne version potentielle : génération de géométrie
        numelem =  model.component('comp1').mesh('mesh1').getNumElem('tri');     % Nombre d’éléments triangulaires
        numvertex = model.component('comp1').mesh('mesh1').getNumVertex();       % Nombre de nœuds (sommets) du maillage
    else                   % Cas 3D
        % [tlm,model]=Geom3Dcad(tlm);
        numelem =  model.component('comp1').mesh('mesh1').getNumElem('tet');     % Nombre de tétraèdres
        numvertex = model.component('comp1').mesh('mesh1').getNumVertex();       % Nombre de nœuds (sommets)
    end

    tlm.var.time_for_geometry=toc;  % Enregistre le temps écoulé pour cette étape dans tlm.var

    %Message=sprintf('\n\t * Mesh Statitics: %u éléments, %u nodes',size(fem.mesh.t,2),size(fem.mesh.p,2));
    Message=sprintf('\n\t * Mesh Statitics: %u éléments, %u nodes',numelem,numvertex);
    % Prépare un message qui résume la taille du maillage (nombre d’éléments et de nœuds)
    disp(Message);  % L’affiche dans la console

    if tlm.conf.log==1
    %    fprintf(fil,'\n\t * Mesh Statitics: %u éléments, %u nodes',size(fem.mesh.t,2),size(fem.mesh.p,2));
        fprintf(fil,'\n\t * Mesh Statitics: %u éléments, %u nodes',numelem,numvertex);
        fprintf(fil,'\n ');
        % Écrit la même info dans le log
    end

    Message=sprintf('\n Generate the Netlist for SPICE simulation (file %s.cir)',tlm.conf.Name);
    % Message indiquant qu’on va maintenant générer la netlist SPICE
    disp(Message);

    if tlm.conf.log==1
        fprintf(fil,'\n Generate Netlist for SPICE simulation (file %s.cir)',tlm.conf.Name);
        fprintf(fil,'\n ');
    end

    % Transfer the fem.mesh structure into matlab arrays to save computing time
    % in the following subroutines

    % Ancienne version basée sur la structure fem utilisée par COMSOL (Legacy) :
    %fem_mesh_p(:,:)=fem.mesh.p(:,:);
    %fem_mesh_t(:,:)=fem.mesh.t(:,:);
    %fem_mesh_e(:,:)=fem.mesh.e(:,:);

    fem_mesh_p(:,:)=model.component('comp1').mesh('mesh1').getVertex; 
    % fem_mesh_p : coordonnées (x,y,z) de tous les sommets du maillage

    if (tlm.conf.dim==2)  
        fem_mesh_t(:,:)=model.component('comp1').mesh('mesh1').getElemEntity('tri');
        % fem_mesh_t (2D) : pour chaque triangle, donne le numéro de domaine auquel il appartient
        fem_mesh_e(:,:)=model.component('comp1').mesh('mesh1').getElem('tri');
        % fem_mesh_e (2D) : pour chaque triangle, indices des nœuds qui le composent
    else
        fem_mesh_t(:,:)=model.component('comp1').mesh('mesh1').getElemEntity('tet');
        % fem_mesh_t (3D) : pour chaque tétraèdre, donne le numéro de domaine associé
        fem_mesh_e(:,:)=model.component('comp1').mesh('mesh1').getElem('tet');
        % fem_mesh_e (3D) : pour chaque tétraèdre, indices des nœuds (0-based) qui le composent
    end
                 
    % Search for the numbers of the points PT1, PT2, ... in the global mesh
    % Flag each domains and fix their conductivity & permittivity

    tic;  % Nouveau chronomètre pour la partie "recherche d’indices + assemblage"

    if (tlm.conf.dim==2)
        [tlm,model]=RechercheIndice2D(tlm,model);
        % Recherche dans le maillage 2D :
        %   - les indices des points particuliers (PT1, PT2, électrodes, etc.)
        %   - l’affectation des domaines (propriétés électriques)
    else
        [tlm,model]=RechercheIndice3Dnew(tlm,model);
        % Même travail que ci-dessus mais pour le maillage 3D
    end

    % Set up the Spice Data Structure
    if (tlm.conf.dim==2)
        [tlm,model]=Remplissage2D(tlm,model);
        % Construit la structure de données du circuit (nœuds, branches) à partir du maillage 2D
    else
        [tlm,model]=Remplissage3D(tlm,model);
        % Idem en 3D
    end

    % Calculation of the values & parameters of the electrical elements
    % (Resistor, Capacitance, Voltage Generator, Current source) of the
    % equivalent electrical circuit
    if (tlm.conf.dim==2)
        [tlm,model]=CalculRC2D(tlm,model);
        % Calcule les valeurs numériques R, C, sources pour le circuit en 2D
    else
        [tlm,model]=CalculRC3D(tlm,model);
        % Idem en 3D
    end

    % Write the input file for the Spice Simulator
    if (tlm.conf.dim==2)
        [tlm,model]=EcriNetList2D(tlm,model);
        % Écrit la netlist SPICE (fichier .cir) pour le cas 2D
    else
        [tlm,model]=EcriNetList3Dnew(tlm,model);
        % Écrit la netlist SPICE pour le cas 3D
    end

    Message=sprintf('\n\t * Circuit Statistics: %u resistances and %u capacitances',tlm.conf.Resistor,tlm.conf.Capacitor);
    % Message indiquant le nombre d’éléments R et C générés dans le circuit
    disp(Message);

    if tlm.conf.log==1
        fprintf(fil,'\n\t * Circuit Statistics: %u resistances and %u capacitances',tlm.conf.Resistor,tlm.conf.Capacitor);
        fprintf(fil,'\n ');
    end

    % Solve the Problem by Transport Lattice Method using SPICE
    Message=sprintf('\n Solve the problem by Transport Lattice Method using SPICE');
    disp(Message);  % Annonce qu’on va lancer la simulation SPICE (TLM)

    if tlm.conf.log==1
        fprintf(fil,'\n Solve the problem by Transport Lattice Method using SPICE');
        fprintf(fil,'\n ');
    end

    % Différentes anciennes lignes de test / chemins utilisant d’autres versions de SPICE :
    %spice='''C:\Documents and Settings\Vincent Senez\Mes documents\simulation\Biocad_3.0\src\wspice3_test test3.cir''';
    %dos('spice');
    %spice='C:\Users\Vincent Senez\Documents\Recherche\Simulation\Biocad_5.0\wspice3_test Simu1.cir';
    %dos(spice);
    %dos('wspice3_test -b -r Calib.chi Calib.cir');
    %dos('..\..\wspice3_test Simu1.cir');
    %dos(strcat("ngspice ", tlm.conf.Name)); % dos('ngspice Simu1.cir');

    % go to the directory that contains ngspice.exe
    cd(tlm.conf.src);  % Se place dans le dossier racine du code
    cd('src');         % Puis dans le sous-dossier 'src' où se trouve ngspice ou le wrapper

    % Run circuit from shell
    % the command must include the '&' character for matlab to continue running and not wait for the end of the execution
    system(sprintf('ngspice \"%s\\%s\\%s.cir\"', tlm.conf.store, tlm.conf.Name, tlm.conf.Name));
    % Appelle ngspice en ligne de commande sur le fichier .cir généré
    % Chemin complet : <store>\<Name>\<Name>.cir

    % move resulting files in tlm.conf.store/tlm.conf.Name (results directory)
    movefile('*.spi_cou', strcat(tlm.conf.store, "\", tlm.conf.Name));
    % Déplace les fichiers *_XX.spi_cou (cartes de potentiel) dans le dossier de la simulation
    movefile('*.spi',     strcat(tlm.conf.store, "\", tlm.conf.Name));
    % Déplace les fichiers .spi (impédances vs fréquence)

    % go to said directory
    cd(strcat(tlm.conf.store, "\", tlm.conf.Name));
    % Se place dans le dossier de cette simulation

    tlm.var.time_for_tlm=toc;
    % Enregistre le temps écoulé pour toute la partie TLM+SPICE (depuis le tic plus haut)

    Message=sprintf('\n\t * Generate ascii file (%s.spi): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
    disp(Message);  % Informe qu’un fichier ASCII .spi contenant l’impédance a été généré

    if tlm.conf.log==1
        fprintf(fil,'\n\t * Generate ascii file (%s.spi): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
        fprintf(fil,'\n ');
    end
            
    Message=sprintf('\n\t * Generate ascii file (%s_XX.spi_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
    disp(Message);  % Informe qu’un fichier *_XX.spi_cou (carte de potentiel) a été généré

    if tlm.conf.log==1
        fprintf(fil,'\n\t * Generate ascii file (%s_XX.spi_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
        fprintf(fil,'\n ');
    end

    % Solve the Problem by Finite Element Method
    if (tlm.conf.calcul==1 || tlm.conf.calcul==2)
        % Si l’utilisateur a demandé un calcul FEM (seul ou combiné avec ANA)

        Message=sprintf('\n Solve the problem by Finite Element Method using COMSOL MULTIPHYSICS routines');
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Solve the problem by Finite Element Method using COMSOL MULTIPHYSICS routines'); 
            fprintf(fil,'\n ');
        end
        
        tic;  % Chronomètre pour la partie FEM
        
        if (tlm.conf.dim==2)
            [tlm,model]=SolFEM2D(tlm,model);
            % Résolution du problème avec COMSOL en 2D (méthode des éléments finis)
        else
            [tlm,model]=SolFEM3D(tlm,model);
            % Résolution FEM en 3D
        end
        
        tlm.var.time_for_fem=toc;
        % Stocke le temps de calcul FEM
        
        Message=sprintf('\n\t * Generate ascii file (%s.fem): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
        disp(Message);
        % Informe de la génération du fichier .fem contenant l’impédance FEM

        if tlm.conf.log==1
            fprintf(fil,'\n\t * Generate ascii file (%s.fem): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
            fprintf(fil,'\n ');
        end
            
        Message=sprintf('\n\t * Generate ascii file (%s_XX.fem_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
        disp(Message);
        % Informe de la génération de la carte de potentiel FEM

        if tlm.conf.log==1
            fprintf(fil,'\n\t * Generate ascii file (%s_XX.fem_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
            fprintf(fil,'\n ');
        end
    end

    % Solve the Problem by Analytical Method
    if ((tlm.conf.calcul==2 || tlm.conf.calcul==3) && tlm.conf.Cell<=1)
        % Si l’utilisateur souhaite un calcul analytique
        % et si le nombre de cellules reste <= 1 (cas simple où une solution analytique existe)
        
        Message=sprintf('\n Solve the problem by Analytical Method');
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Solve the problem by Analytical Method'); 
            fprintf(fil,'\n ');
        end
        
        tic;  % Chronomètre pour la partie analytique
        
        if (tlm.conf.dim==2)
           [tlm,fem]=SolANA2D(tlm,fem);
           % Résolution analytique 2D (retourne aussi éventuellement des infos FEM locales)
        else
           [tlm,model]=SolANA3D(tlm,model);
           % Résolution analytique en 3D
        end
        
        tlm.var.time_for_ana=toc;
        % Stockage du temps de calcul analytique
        
        Message=sprintf('\n\t * Generate ascii file (%s.ana): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
        disp(Message);
        % Informe de la génération du fichier .ana (impédance analytique)

        if tlm.conf.log==1
            fprintf(fil,'\n\t * Generate ascii file (%s.ana): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
            fprintf(fil,'\n ');
        end
        
        Message=sprintf('\n\t * Generate ascii file (%s_XX.ana_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
        disp(Message);
        % Informe de la génération du fichier *_XX.ana_cou (carte de potentiel analytique)

        if tlm.conf.log==1
            fprintf(fil,'\n\t * Generate ascii file (%s_XX.ana_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
            fprintf(fil,'\n ');
        end
        
    elseif ((tlm.conf.calcul==2 || tlm.conf.calcul==3) && tlm.conf.Cell>=2)
        % L’utilisateur demande un calcul analytique mais le nombre de cellules est ≥ 2,
        % donc aucune solution analytique simple n’est disponible.
        
        Message=sprintf('\n Solve the problem by Analytical Method');
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Solve the problem by Analytical Method'); 
            fprintf(fil,'\n ');
        end

        Message=sprintf('\n\t * There is no analytical solution to this problem');
        disp(Message);  % Indique clairement qu’il n’existe pas de solution analytique

        if tlm.conf.log==1
            fprintf(fil,'\n\t * There is no analytical solution to this problem'); 
            fprintf(fil,'\n ');
        end
    end

    % Affichage récapitulatif des temps de calcul suivant le mode choisi
    if tlm.conf.calcul==2
        % Mode : TLM + FEM + ANA (si applicable)
        Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u; Time for ANA is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm, tlm.var.time_for_fem, tlm.var.time_for_ana);
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u; Time for ANA is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm, tlm.var.time_for_fem, tlm.var.time_for_ana);
            fprintf(fil,'\n ');
        end

    elseif tlm.conf.calcul==1
        % Mode : TLM + FEM
        Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm, tlm.var.time_for_fem);
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm, tlm.var.time_for_fem);
            fprintf(fil,'\n ');
        end

    elseif tlm.conf.calcul==3
        % Mode : TLM + ANA
        Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u; Time for ANA is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm, tlm.var.time_for_ana);
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u; Time for ANA is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm, tlm.var.time_for_ana);
            % fprint   % (probable typo ou commentaire laissé par l’auteur)
        end

    else
        % Mode par défaut : TLM seul (pas FEM, pas ANA)
        Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm);
        disp(Message);

        if tlm.conf.log==1
            fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u', ...
                        tlm.var.time_for_geometry, tlm.var.time_for_tlm);
            fprintf(fil,'\n ');
        end
    end

    Message=sprintf('\n ******* End the Simulation');
    disp(Message);  % Message de fin de simulation dans la console

    if tlm.conf.log==1
        fprintf(fil,'\n ******* End the Simulation');
        fprintf(fil,'\n ');
        % Écrit la fin de simulation dans le log
    end
end
