%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%
%   Release 1.0 : January 2019
%
%   Function : Compute the various analysis
%
%   Called by : Biocad
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm,model]=Compute(tlm,fil, model)

% Clear command window
clc;

% Close all figure windows
if tlm.conf.fig>0
    for i=tlm.conf.fig-1:-1:1
        figure(i);
        close(i);
    end
        tlm.conf.fig=0;
end

% Dock figures in Matlab GUI
set(0,'DefaultFigureWindowStyle', 'normal') % 'docked'

% Print on the Command Window of Matlab
Message=sprintf('\n ******* Start the Simulation');
disp(Message);

% Initialization
clear global fem_mesh_p;
clear global fem_mesh_t;
clear global fem_mesh_e;

global fem_mesh_p;
global fem_mesh_t;
global fem_mesh_e;

% Open log file

if tlm.conf.log==1

    fprintf(fil, '********************************************************************************\n');            
    fprintf(fil, '*\n');            
    fprintf(fil, '*                           Log File Generated by\n'); 
    fprintf(fil, '*\n');            
    fprintf(fil, '*                              BIOCAD Program\n');            
    fprintf(fil, '*                               Release 1.0\n');            
    fprintf(fil, '*\n');            
    fprintf(fil, '*   Authors: Vincent Senez\n'); 
    fprintf(fil, '*\n');            
    fprintf(fil, '*   Release 1.0 : January 2019\n');     
    fprintf(fil, '*\n');            
    fprintf(fil, '********************************************************************************\n');            
    fprintf(fil, '\n');            

    % Date and Time

    a=clock;
    fprintf(fil,'\n Date: %u - %u - %u, Time: %u:%u:%u',fix(a(3)),fix(a(2)),fix(a(1)),fix(a(4)),fix(a(5)),fix(a(6)));
    fprintf(fil,'\n ');

    fprintf(fil,'\n Files are saved in directory: ');
    fprintf(fil,'\n\t ''%s''', strcat(tlm.conf.store, "\", tlm.conf.Name));
    fprintf(fil,'\n ');

    fprintf(fil,'\n The parameters of the analysis are:');

    % Write values of all Parameters in log file
    WritePara(tlm,fil);
end

if tlm.conf.log==1
    fprintf(fil,'\n ******* Start the Simulation');
    fprintf(fil,'\n ');
end

Message=sprintf('\n Files are saved in directory: ''%s''', strcat(tlm.conf.store, "\", tlm.conf.Name));
disp(Message);

% Drawing of the geometry

Message=sprintf('\n Draw the Geometry with COMSOL MULTIPHYSICS routines');
disp(Message);

if tlm.conf.log==1
    fprintf(fil,'\n Draw the Geometry with COMSOL MULTIPHYSICS routines');
    fprintf(fil,'\n ');
end

%Draw the structure

tic;

if (tlm.conf.dim==2)  
    %[tlm,model]=Geom2Dcad(tlm);
    numelem=model.component('comp1').mesh('mesh1').getNumElem('tri');
    numvertex=model.component('comp1').mesh('mesh1').getNumVertex();
else                   
    % [tlm,model]=Geom3Dcad(tlm);
    numelem=model.component('comp1').mesh('mesh1').getNumElem('tet');
    numvertex=model.component('comp1').mesh('mesh1').getNumVertex();
end

tlm.var.time_for_geometry=toc;

%Message=sprintf('\n\t * Mesh Statitics: %u �l�ments, %u nodes',size(fem.mesh.t,2),size(fem.mesh.p,2));
Message=sprintf('\n\t * Mesh Statitics: %u �l�ments, %u nodes',numelem,numvertex);
disp(Message);
if tlm.conf.log==1
%    fprintf(fil,'\n\t * Mesh Statitics: %u �l�ments, %u nodes',size(fem.mesh.t,2),size(fem.mesh.p,2));
    fprintf(fil,'\n\t * Mesh Statitics: %u �l�ments, %u nodes',numelem,numvertex);
    fprintf(fil,'\n ');
end
Message=sprintf('\n Generate the Netlist for SPICE simulation (file %s.cir)',tlm.conf.Name);
disp(Message);
if tlm.conf.log==1
    fprintf(fil,'\n Generate Netlist for SPICE simulation (file %s.cir)',tlm.conf.Name);
    fprintf(fil,'\n ');
end

% Transfer the fem.mesh structure into matlab arrays to save computing time
% in the following subroutines

%fem_mesh_p(:,:)=fem.mesh.p(:,:);
%fem_mesh_t(:,:)=fem.mesh.t(:,:);
%fem_mesh_e(:,:)=fem.mesh.e(:,:);

fem_mesh_p(:,:)=model.component('comp1').mesh('mesh1').getVertex; % coordinates of vertex
% Convertir les coordonnées brutes du maillage en mètres
fem_mesh_p(:,:) = fem_mesh_p(:,:) * tlm.var.scale;

if (tlm.conf.dim==2)  
    fem_mesh_t(:,:)=model.component('comp1').mesh('mesh1').getElemEntity('tri');
    fem_mesh_e(:,:)=model.component('comp1').mesh('mesh1').getElem('tri');
else
    fem_mesh_t(:,:)=model.component('comp1').mesh('mesh1').getElemEntity('tet');%store for each tetrahedron the domain (number) it belongs to
    fem_mesh_e(:,:)=model.component('comp1').mesh('mesh1').getElem('tet'); % nodes numbers (from 0) of the 4 nodes of the current elements
end
             
% Search for the numbers of the points PT1, PT2, ... in the global mesh
% Flag each domains and fix their conductivity & permittivity

tic;

if (tlm.conf.dim==2)
    [tlm,model]=RechercheIndice2D(tlm,model);
else
    [tlm,model]=RechercheIndice3Dnew(tlm,model);
end

% Set up the Spice Data Structure

if (tlm.conf.dim==2)
    [tlm,model]=Remplissage2D(tlm,model);
else
    [tlm,model]=Remplissage3D(tlm,model);
end

% Calculation of the values & parameters of the electrical elements
% (Resistor, Capacitance, Voltage Generator, Current source) of the
% equivalent electrical circuit

if (tlm.conf.dim==2)
    [tlm,model]=CalculRC2D(tlm,model);
else
    [tlm,model]=CalculRC3D(tlm,model);
end

% Write the input file for the Spice Simulator

if (tlm.conf.dim==2)
    [tlm,model]=EcriNetList2D(tlm,model);
else
    [tlm,model]=EcriNetList3Dnew(tlm,model);
end
Message=sprintf('\n\t * Circuit Statistics: %u resistances and %u capacitances',tlm.conf.Resistor,tlm.conf.Capacitor);
disp(Message);
if tlm.conf.log==1
    fprintf(fil,'\n\t * Circuit Statistics: %u resistances and %u capacitances',tlm.conf.Resistor,tlm.conf.Capacitor);
    fprintf(fil,'\n ');
end

% Solve the Problem by Transport Lattice Method using SPICE

Message=sprintf('\n Solve the problem by Transport Lattice Method using SPICE');
disp(Message);
if tlm.conf.log==1
    fprintf(fil,'\n Solve the problem by Transport Lattice Method using SPICE');
    fprintf(fil,'\n ');
end

%spice='''C:\Documents and Settings\Vincent Senez\Mes documents\simulation\Biocad_3.0\src\wspice3_test test3.cir''';
%dos('spice');
%spice='C:\Users\Vincent Senez\Documents\Recherche\Simulation\Biocad_5.0\wspice3_test Simu1.cir';
%dos(spice);
%dos('wspice3_test -b -r Calib.chi Calib.cir');
%dos('..\..\wspice3_test Simu1.cir');
%dos(strcat("ngspice ", tlm.conf.Name)); % dos('ngspice Simu1.cir');

% go to the directory that contains ngspice.exe
cd(tlm.conf.src);
cd('src');

% Run circuit from shell
% the command must include the '&' character for matlab to continue running and not wait for the end of the execution
xycePath = 'C:\Program Files\XyceNF_7.10\bin\Xyce.exe';
ngspicePath = fullfile(pwd, 'ngspice.exe');
cirPath = sprintf('%s\\%s\\%s.cir', tlm.conf.store, tlm.conf.Name, tlm.conf.Name);

% =========================================================================
% LANCEMENT DE XYCE EN PARALLÈLE VIA LINUX (WSL)
% =========================================================================

% 1. Définir le nombre de cœurs à utiliser (on met 10 pour garder de la marge pour Windows)
num_cores = '4'; 

% 2. Le chemin de ton exécutable Xyce compilé sous Linux
xyceLinuxPath = '/usr/local/xyce_mpi/bin/Xyce';

% 3. Construire le chemin du fichier .cir sous Windows
cirPathWindows = sprintf('%s\\%s\\%s.cir', tlm.conf.store, tlm.conf.Name, tlm.conf.Name);

if exist(cirPathWindows, 'file')
    % 4. Traduire le chemin Windows (C:\...) vers Linux (/mnt/c/...)
    % "wsl wslpath -a" demande à Ubuntu de faire la traduction
    [status, cirPathLinux] = system(sprintf('wsl wslpath -a "%s"', cirPathWindows));
    
    if status ~= 0
        error('Erreur lors de la traduction du chemin Windows vers Linux via WSL.');
    end
    
    % Nettoyer le chemin (enlever les retours à la ligne invisibles)
    cirPathLinux = strtrim(cirPathLinux);
    
    % 5. Construire la commande finale de calcul parallèle
    % - wsl : passe la commande à Linux
    % - mpirun --use-hwthread-cpus -n 10 : distribue le calcul sur 10 processus isolés
    commande_xyce = sprintf('wsl mpirun --use-hwthread-cpus -n %s %s "%s"', num_cores, xyceLinuxPath, cirPathLinux);
    
    disp(['Lancement fulgurant de Xyce Parallel (WSL) sur ', num_cores, ' coeurs...']);
    
    % 6. Lancement de la simulation !
    tic; % Démarre un chronomètre
    system(commande_xyce);
    temps_xyce = toc; % Arrête le chronomètre
    
    disp(['Simulation Xyce terminée en ', num2str(temps_xyce), ' secondes !']);
else
    error('Le fichier .cir n''a pas été trouvé pour la simulation.');
end

% move resulting files in tlm.conf.store/tlm.conf.Name ( results directory)
dstDir = strcat(tlm.conf.store, "\\", tlm.conf.Name);
if ~isempty(dir('*.spi'))
    movefile('*.spi', dstDir);
end
if ~isempty(dir('*.spi_cou'))
    movefile('*.spi_cou', dstDir);
end
if ~isempty(dir('*.prn'))
    movefile('*.prn', dstDir);
end
if ~isempty(dir('*.csv'))
    movefile('*.csv', dstDir);
end

% go to said directory
cd(strcat(tlm.conf.store, "\", tlm.conf.Name));

tlm.var.time_for_tlm=toc;

Message=sprintf('\n\t * Generate ascii file (%s.spi): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
disp(Message);
if tlm.conf.log==1
    fprintf(fil,'\n\t * Generate ascii file (%s.spi): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
    fprintf(fil,'\n ');
end
        
Message=sprintf('\n\t * Generate ascii file (%s_XX.spi_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
disp(Message);
if tlm.conf.log==1
    fprintf(fil,'\n\t * Generate ascii file (%s_XX.spi_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
    fprintf(fil,'\n ');
end

% Solve the Problem by Finite Element Method

if (tlm.conf.calcul==1 || tlm.conf.calcul==2)
    
    Message=sprintf('\n Solve the problem by Finite Element Method using COMSOL MULTIPHYSICS routines');
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Solve the problem by Finite Element Method using COMSOL MULTIPHYSICS routines'); 
        fprintf(fil,'\n ');
    end
    
    tic;
    
    if (tlm.conf.dim==2)
        [tlm,model]=SolFEM2D(tlm,model);
    else
        [tlm,model]=SolFEM3D(tlm,model);
    end
    
    tlm.var.time_for_fem=toc;
    
    Message=sprintf('\n\t * Generate ascii file (%s.fem): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n\t * Generate ascii file (%s.fem): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
        fprintf(fil,'\n ');
    end
        
    Message=sprintf('\n\t * Generate ascii file (%s_XX.fem_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n\t * Generate ascii file (%s_XX.fem_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
        fprintf(fil,'\n ');
    end
    
end

% Solve the Problem by Analytical Method

if ((tlm.conf.calcul==2 || tlm.conf.calcul==3) && tlm.conf.Cell<=1)
    
    Message=sprintf('\n Solve the problem by Analytical Method');
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Solve the problem by Analytical Method'); 
        fprintf(fil,'\n ');
    end
    
    tic;
    
    if (tlm.conf.dim==2)
       [tlm,fem]=SolANA2D(tlm,fem);
    else
       [tlm,model]=SolANA3D(tlm,model);
    end
    
    tlm.var.time_for_ana=toc;
    
    Message=sprintf('\n\t * Generate ascii file (%s.ana): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n\t * Generate ascii file (%s.ana): ''Electrical Impedance versus Frequency''', tlm.conf.Name);
        fprintf(fil,'\n ');
    end
    
    Message=sprintf('\n\t * Generate ascii file (%s_XX.ana_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n\t * Generate ascii file (%s_XX.ana_cou): ''2D/3D map of the Electric Potential''', tlm.conf.Name);
        fprintf(fil,'\n ');
    end
    
elseif ((tlm.conf.calcul==2 || tlm.conf.calcul==3) && tlm.conf.Cell>=2)
    
    Message=sprintf('\n Solve the problem by Analytical Method');
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Solve the problem by Analytical Method'); 
        fprintf(fil,'\n ');
    end

    Message=sprintf('\n\t * There is no analytical solution to this problem');
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n\t * There is no analytical solution to this problem'); 
        fprintf(fil,'\n ');
    end

end

if tlm.conf.calcul==2
    Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u; Time for ANA is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm,tlm.var.time_for_fem,tlm.var.time_for_ana);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u; Time for ANA is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm,tlm.var.time_for_fem,tlm.var.time_for_ana);
        fprintf(fil,'\n ');
    end
elseif tlm.conf.calcul==1
    Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm,tlm.var.time_for_fem);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u; Time for FEM is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm,tlm.var.time_for_fem);
        fprintf(fil,'\n ');
    end
elseif tlm.conf.calcul==3
    Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u; Time for ANA is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm,tlm.var.time_for_ana);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u; Time for ANA is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm,tlm.var.time_for_ana);
        % fprint
    end
else
    Message=sprintf('\n Time for Geometry is: %u; Time for TLM is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm);
    disp(Message);
    if tlm.conf.log==1
        fprintf(fil,'\n Time for Geometry is: %u; Time for TLM is: %u', tlm.var.time_for_geometry,...
                    tlm.var.time_for_tlm);
        fprintf(fil,'\n ');
    end
end

Message=sprintf('\n ******* End the Simulation');
disp(Message);
if tlm.conf.log==1
    fprintf(fil,'\n ******* End the Simulation');
    fprintf(fil,'\n ');
end

