%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%   
%   Release 1.0 : January 2019
% 
%
%   Routine EcritNetList3D called by Compute.m
%
%   Function: Write the input file (e.g.: xx.sp, xx.cir) for the Spice Simulator 
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm, model] = EcriNetList3Dnew(tlm, model)

    % Global Mesh Data
    global fem_mesh_p;
    global fem_mesh_e;
    global fem_mesh_t;

    tlm.conf.Resistor = 0;
    tlm.conf.Capacitor = 0;
    scale = tlm.var.scale;

    % File management
    name_cir = sprintf('%s.cir', tlm.conf.Name);
    fid = fopen(name_cir, 'w');
    fprintf('\n\t . Écriture de la Netlist SPICE : %s', name_cir);

    % --- 1. HEADER SPICE ---
    fprintf(fid, '* Spice Netlist Generated by BIOCAD (Refactored 2026)\n');
    fprintf(fid, '***************************************************\n');

    % --- 2. ANALYSE ET CONTRÔLE SPICE ---
    fprintf(fid, '.CONTROL\n');
    fprintf(fid, '  DESTROY ALL\n');
    fprintf(fid, '  AC DEC %f %f %f\n', tlm.var.frequence.step, tlm.var.frequence.min, tlm.var.frequence.max);
    
    % Calcul des sorties selon le nombre de points
    if tlm.conf.points <= 2
        fprintf(fid, '  WRITE %s.spi vdb(%u,%u)-vdb(%u)-66 vp(%u,%u)-vp(%u)\n', ...
                tlm.conf.Name, tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1, ...
                tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec2);
    elseif tlm.conf.points == 4
        fprintf(fid, '  WRITE %s.spi vdb(%u)-vdb(%u)-66 vp(%u,%u)-vp(%u)\n', ...
                tlm.conf.Name, tlm.ind.pt.mesu2, tlm.ind.pt.mesu1, tlm.ind.pt.elec1, ...
                tlm.ind.pt.mesu2, tlm.ind.pt.mesu1, tlm.ind.pt.elec1);
    end
    fprintf(fid, '.ENDC\n\n');

    % --- 3. EXCITATIONS (FACTORISÉES) ---
    % Source principale
    fprintf(fid, 'Vin\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec2, tlm.var.v0);
    fprintf(fid, 'Rg\t%u\t0\t50e-5\n', tlm.ind.pt.elec1);

    % Sources de surface (Factorisation par boucles)
    fields = {'supa', 'supb', 'supc', 'supd', 'supe', 'supf', 'supg'};
    num_layers = length(tlm.ind.pt.elec2supa);
    
    for k = 1:num_layers
        for f = 1:length(fields)
            % Écriture dynamique des Vin
            fname = ['elec2' fields{f}];
            if isfield(tlm.ind.pt, fname) && k <= length(tlm.ind.pt.(fname))
                fprintf(fid, 'V%d%s\t%u\t0\tDC 0 AC %f\n', k, fields{f}, tlm.ind.pt.(fname)(k), tlm.var.v0);
            end
            % Écriture dynamique des Rg (Ground)
            gname = ['elec1' fields{f}];
            if isfield(tlm.ind.pt, gname) && k <= length(tlm.ind.pt.(gname))
                fprintf(fid, 'R%d%s\t%u\t0\t50e-5\n', k, fields{f}, tlm.ind.pt.(gname)(k));
            end
        end
    end

    % --- 4. PRÉ-CALCUL DES SURFACES DE NOEUDS (OPTIMISATION CRITIQUE) ---
    % On calcule l'aire associée à chaque nœud de bordure une seule fois
    fprintf('\n\t . Pré-calcul des surfaces de membrane...');
    node_areas = zeros(size(fem_mesh_p, 2), 1);
    for j = 1:size(fem_mesh_e, 2)
        p1 = fem_mesh_p(:, fem_mesh_e(1,j));
        p2 = fem_mesh_p(:, fem_mesh_e(2,j));
        p3 = fem_mesh_p(:, fem_mesh_e(3,j));
        % Aire du triangle (Héron)
        a = norm(p1-p2); b = norm(p2-p3); c = norm(p3-p1);
        s = (a+b+c)/2;
        area_tri = sqrt(max(0, s*(s-a)*(s-b)*(s-c)));
        % Distribution de l'aire aux 3 nœuds
        node_areas(fem_mesh_e(1:3, j)) = node_areas(fem_mesh_e(1:3, j)) + (area_tri/3);
    end

    % --- 5. ÉCRITURE DES COMPOSANTS (R // C) ---
    fprintf('\n\t . Écriture des segments du circuit...');
    for i = 1:size(tlm.result, 2)
        for j = 1:size(tlm.result{i}, 2)
            res = tlm.result{i}{j};
            target_node = res(1);
            R_val = res(3);
            C_val = max(1e-25, res(4)); % Sécurité SPICE pour C > 0
            h_flag = res(7); % Flag de membrane

            % Écriture Résistance et Capacité de Bulk
            if R_val < 1e12 % Si pas un isolant pur
                fprintf(fid, 'R%u_%u\t%u\t%u\t%17.16e\n', i, target_node, i, target_node, R_val);
                tlm.conf.Resistor = tlm.conf.Resistor + 1;
            end
            fprintf(fid, 'C%u_%u\t%u\t%u\t%17.16e\n', i, target_node, i, target_node, C_val);
            tlm.conf.Capacitor = tlm.conf.Capacitor + 1;

            % --- LOGIQUE DE MEMBRANE (Utilise le pré-calcul) ---
            if h_flag > 0
                aire = node_areas(i) * (scale^2);
                if aire > 0
                    % Détermination des propriétés selon le flag h
                    % h=3,4: MembCel, h=5,6: MembNuc, h=7,8: MembMit...
                    [eps_m, thick_m, tag] = get_membrane_props(h_flag, tlm);
                    
                    if ~isempty(tag)
                        C_memb = (eps_m * aire) / thick_m;
                        fprintf(fid, 'Cm%s_%u\t%u\t%u\t%17.16e\n', tag, i, i, target_node, C_memb);
                        tlm.conf.Capacitor = tlm.conf.Capacitor + 1;
                    end
                end
            end
        end
    end

    fclose(fid);
    fprintf('\n\t . Netlist terminée. %d Résistances, %d Capacités.\n', tlm.conf.Resistor, tlm.conf.Capacitor);
end

% --- FONCTION AUXILIAIRE : PROPRIÉTÉS DE MEMBRANE ---
function [eps_m, thick_m, tag] = get_membrane_props(h, tlm)
    tag = ''; eps_m = 0; thick_m = 1;
    switch h
        case {3, 4, 9, 10} % Membrane Cellulaire (Cell 1 ou 2)
            c_idx = floor((h-1)/6) + 1; % Déduit 1 ou 2
            eps_m = tlm.var.eps.MembCel(c_idx);
            thick_m = tlm.var.EpaisseurMembrane;
            tag = sprintf('C%d', c_idx);
        case {5, 6, 11, 12} % Membrane Nucléaire
            c_idx = floor((h-1)/6) + 1;
            eps_m = tlm.var.eps.MembNuc(c_idx);
            thick_m = tlm.var.EpaisseurNucleus;
            tag = sprintf('N%d', c_idx);
        case {7, 8, 13, 14} % Membrane Mitochondriale
            c_idx = floor((h-1)/6) + 1;
            eps_m = tlm.var.eps.MembMit(c_idx);
            thick_m = tlm.var.EpaisseurMitochon;
            tag = sprintf('M%d', c_idx);
    end
end