%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%   
%   Release 1.0 : January 2019
% 
%
%   Routine EcritNetList3D called by Compute.m
%
%   Function: Write the input file (e.g.: xx.sp, xx.cir) for the Spice Simulator 
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm,model] = EcriNetList3Dnew(tlm,model)

% Initialization
global fem_mesh_p;
global fem_mesh_e;
global fem_mesh_t;

tlm.conf.Resistor = 0;
tlm.conf.Capacitor = 0;

name1 = sprintf('%s.cir', tlm.conf.Name);        % Name of the file for the Net List
fid = fopen(name1, 'w');                         % Open the File

name2 = sprintf('%s.cor', tlm.conf.Name);        % Name of the file for the coordinates of each node
fie = fopen(name2, 'w');                         % Open the File

% Write Headers
fprintf(fid, '%s.cir\n', tlm.conf.Name);
fprintf(fid, '********************************************************************************\n');            
fprintf(fid, '*\n');            
fprintf(fid, '* Spice Netlist Generated by\n'); 
fprintf(fid, '*\n');            
fprintf(fid, '* BIOCAD Program\n');            
fprintf(fid, '* Release 1.0\n');            
fprintf(fid, '*\n');            
fprintf(fid, '* Authors: Vincent Senez\n'); 
fprintf(fid, '*\n');            
fprintf(fid, '* Release 1.0 : January 2019\n');          
fprintf(fid, '*\n');            
fprintf(fid, '********************************************************************************\n');

% Define the type of analysis
fprintf(fid, '.CONTROL \n');
fprintf(fid, '  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC %f %f %f \n', tlm.var.frequence.step, tlm.var.frequence.min, tlm.var.frequence.max);

% Write measurements commands
if tlm.conf.points == 2
    fprintf(fid, '  WRITE %s.spi vdb(%u,%u)-vdb(%u)-66 vp(%u,%u)-vp(%u) \n', ...
            tlm.conf.Name, tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1, ...
            tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1);
elseif tlm.conf.points == 4
    fprintf(fid, '  WRITE %s.spi vdb(%u)-vdb(%u)-66 vp(%u,%u)-vp(%u) \n', ...
            tlm.conf.Name, tlm.ind.pt.mesu2, tlm.ind.pt.mesu1, tlm.ind.pt.elec1, ...
            tlm.ind.pt.mesu2, tlm.ind.pt.mesu1, tlm.ind.pt.elec1);
end

fprintf(fid, '  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC 1 %f %f \n', tlm.var.frequence.min, tlm.var.frequence.min);
fprintf(fid, '  WRITE %s all \n', strcat(tlm.conf.Name, "_", num2str(tlm.var.frequence.min), "Hz.spi_cou"));

fprintf(fid, '  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC 1 %f %f \n', tlm.var.frequence.int, tlm.var.frequence.int);
fprintf(fid, '  WRITE %s.spi_cou all \n', strcat(tlm.conf.Name, "_", num2str(tlm.var.frequence.int), "Hz"));

fprintf(fid, '  DESTROY ALL \n'); 
fprintf(fid, '  AC DEC 1 %f %f \n', tlm.var.frequence.max, tlm.var.frequence.max);
fprintf(fid, '  WRITE %s.spi_cou all \n', strcat(tlm.conf.Name, "_", num2str(tlm.var.frequence.max), "Hz"));

fprintf(fid, '.ENDC \n');
                                                                                            
fprintf(fid, 'Vin\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec2, tlm.var.v0); % Left outer electrode
fprintf(fid, 'Rg\t%u\t0\t50e-5\n', tlm.ind.pt.elec1);                   % Right outer electrode


% =========================================================================
% FIN DE LA SECTION OPTIMISÉE
% =========================================================================

% LA SUITE DE VOTRE CODE ORIGINAL COMMENCE ICI 
% (Par exemple, la définition des capacités parasites, les boucles de maillage, etc.)
% ...