%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%   
%   Release 1.0 : January 2019
% 
%
%   Routine EcritNetList3D called by Compute.m
%
%   Function: Write the input file (e.g.: xx.sp, xx.cir) for the Spice Simulator 
%
%   Remarks:
%   tlm.result(numeroduptincident)={numduptcible1, numtetra[], R1, C1, R2, C2, h ...}
%   with h=1 : If the segment is in the outer electrodes and one edge is in contact with the organic medium (serum) 
%          2 : If the segment is in the organic medium and one edge is in contact with the outer electrodes 
%          3 : If the segment is in the cytoplasm(1) and one edge is in contact with the organic medium (serum) 
%          4 : If the segment is in the organic medium and one edge is in contact with the cytoplasm(1) 
%          5 : If the segment is in the cytoplasm(1) and one edge is in contact with the nucleus(1) 
%          6 : If the segment is in the nucleus(1) and one edge is in contact with the cytoplasm(1)
%          7 : If the segment is in the cytoplasm(1) and one edge is in contact with the mitochon(1) 
%          8 : If the segment is in the mitochon(1) and one edge is in contact with the cytoplasm(1)
%          9 : If the segment is in the cytoplasm(2) and one edge is in contact with the organic medium
%         10 : If the segment is in the organic medium and one edge is in contact with the cytoplasm(2) 
%         11 : If the segment is in the cytoplasm(2) and one edge is in contact with the nucleus(2) 
%         12 : If the segment is in the nucleus(2) and one edge is in contact with the cytoplasm(2)
%         13 : If the segment is in the cytoplasm(2) and one edge is in contact with the mitochon(2) 
%         14 : If the segment is in the mitochon(2) and one edge is in contact with the cytoplasm(2)
%          Length of the segment : If the segment is at the interface (for parasitics with ST2)
%
%   tlm.geom.boundaryEE{numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   outer electrodes - organic medium (serum) (for the parasitics with ST1)
%   tlm.geom.boundaryEC{numcell,numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   cytoplasm(1) or (2) - organic medium (serum)
%   tlm.geom.boundaryEN{numcell,numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   nucleus(1) or (2) - cytoplasm (1) or (2)
%   tlm.geom.boundaryEM{numcell,numdupt}=0  or length of the segment if the node is at the interface between the 
%                                   mitochondria(1) or (2) - cytoplasm(1) or (2)
%
%   tlm.geom.airvol(numdutrg)= sixth of the volume of the tetrahedron
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm,model]=EcriNetList3Dnew(tlm,model)

% Initialization
global fem_mesh_p;
global fem_mesh_e;
global fem_mesh_t;

tlm.conf.Resistor = 0;
tlm.conf.Capacitor = 0;

name1 = sprintf('%s.cir', tlm.conf.Name);        % Name of the file for the Net List
fid = fopen(name1, 'w');                         % Open the File

name2 = sprintf('%s.cor', tlm.conf.Name);        % Name of the file for the coordinates of each node
fie = fopen(name2, 'w');                         % Open the File

% Write Headers
fprintf(fid, '%s.cir\n', tlm.conf.Name);
fprintf(fid, '********************************************************************************\n');            
fprintf(fid, '*\n');            
fprintf(fid, '* Spice Netlist Generated by\n'); 
fprintf(fid, '*\n');            
fprintf(fid, '* BIOCAD Program\n');            
fprintf(fid, '* Release 1.0\n');            
fprintf(fid, '*\n');            
fprintf(fid, '* Authors: Vincent Senez\n'); 
fprintf(fid, '*\n');            
fprintf(fid, '* Release 1.0 : January 2019\n');          
fprintf(fid, '*\n');            
fprintf(fid, '********************************************************************************\n');

% Xyce-compatible analysis and output directives.
fprintf(fid, '.AC DEC %f %f %f\n', tlm.var.frequence.step, tlm.var.frequence.min, tlm.var.frequence.max);

% Modified by: Tina - Build connectivity mask for SPICE node validation
% This ensures electrode and measurement nodes are connected to the circuit
connected_mask = build_spice_node_mask(tlm, fem_mesh_p);

if ~isempty(connected_mask) && any(connected_mask)
    [tlm.ind.pt.elec1, moved1] = nearest_connected_node(tlm.ind.pt.elec1, fem_mesh_p, connected_mask);
    [tlm.ind.pt.elec2, moved2] = nearest_connected_node(tlm.ind.pt.elec2, fem_mesh_p, connected_mask);
    
    % Modified by: Tina - Log electrode node mapping decisions
    % Critical for debugging if results are unexpectedly high/low
    if moved1
        fprintf('\n\t . Warning: electrode 1 node was isolated; remapped to node %u', tlm.ind.pt.elec1);
    else
        fprintf('\n\t . Electrode 1 (excitation): node %u (connected)', tlm.ind.pt.elec1);
    end
    if moved2
        fprintf('\n\t . Warning: electrode 2 node was isolated; remapped to node %u', tlm.ind.pt.elec2);
    else
        fprintf('\n\t . Electrode 2 (return): node %u (connected)', tlm.ind.pt.elec2);
    end
    
    % Modified by: Tina - Store node remapping status for validation report
    tlm.node_mapping.elec1_remapped = moved1;
    tlm.node_mapping.elec2_remapped = moved2;
end

% Modified by: Tina - Extract measurement nodes (may differ from excitation electrodes)
% In 4-point measurement configuration, measurement nodes can be at different locations
mesu1 = tlm.ind.pt.elec1;
mesu2 = tlm.ind.pt.elec2;
measurement_mode = 'default';

if isfield(tlm.ind, 'pt') && isfield(tlm.ind.pt, 'mesu1') && ~isempty(tlm.ind.pt.mesu1)
    mesu1 = tlm.ind.pt.mesu1;
    measurement_mode = 'custom';
end
if isfield(tlm.ind, 'pt') && isfield(tlm.ind.pt, 'mesu2') && ~isempty(tlm.ind.pt.mesu2)
    mesu2 = tlm.ind.pt.mesu2;
    measurement_mode = 'custom';
end

% Modified by: Tina - Log measurement node configuration
fprintf('\n\t . Measurement nodes: mesu1=%u, mesu2=%u (%s mode)', mesu1, mesu2, measurement_mode);

% 4-point impedance measurement: Z = Rg * V(mesu2) / V(mesu1)
% In dB (Xyce notation): Z_dB = VDB(mesu2) - VDB(mesu1) + 20*log10(Rg)
% With Rg=50e-6 Ω: 20*log10(50e-6) ≈ -86.02 dB
if tlm.conf.points == 2
    fprintf(fid, '.PRINT AC FORMAT=CSV FREQ {VDB(%u,%u)-VDB(%u)-86} {VP(%u,%u)-VP(%u)}', ...
            tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1, ...
            tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1);
elseif tlm.conf.points == 4
    fprintf(fid, '.PRINT AC FORMAT=CSV FREQ {VDB(%u)-VDB(%u)-86} {VP(%u,%u)-VP(%u)}', ...
            mesu2, mesu1, ...
            tlm.ind.pt.elec1, mesu2, mesu1);
else
    fprintf(fid, '.PRINT AC FORMAT=CSV FREQ {VDB(%u,%u)-VDB(%u)-86} {VP(%u,%u)-VP(%u)}', ...
            tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1, ...
            tlm.ind.pt.elec2, tlm.ind.pt.elec1, tlm.ind.pt.elec1);
end

% Disable per-node VR() dumping by default: in large extracted circuits,
% many mesh node IDs do not exist as SPICE nodes after boundary renaming.
% Keeping only the impedance expressions above avoids undefined-symbol aborts.
fprintf(fid, '\n');

% Modified by: Tina - Define SPICE voltage source for excitation (Vin)
% This drives the impedance measurement through one electrode
fprintf(fid, 'Vin\t%u\t0\tDC 0 AC %f\n', tlm.ind.pt.elec2, tlm.var.v0); % Excitation electrode
fprintf('\n\t . Excitation source: Vin connected to node %u with amplitude %.3e V', tlm.ind.pt.elec2, tlm.var.v0);

% Modified by: Tina - Define SPICE source impedance (Rg)
% 50Ω source impedance is standard for RF measurements
% Converted to 50e-5 Ω for internal calculations (SI units)
fprintf(fid, 'Rg\t%u\t0\t50e-5\n', tlm.ind.pt.elec1);  % Return electrode
fprintf('\n\t . Source impedance: Rg (50μΩ) connected to node %u', tlm.ind.pt.elec1);

%Write the value of all electrical components in the .cir file

% ===== INTERFACE-AWARE R/C COMPONENT TRACKING =====
% Initialize interface counters for tracking which interface types contribute to the circuit
interface_stats = struct();
interface_stats.electrode_medium = 0;  % Outer electrode - organic medium (serum) interface
interface_stats.cell_membrane_1 = 0;   % Cell 1 cytoplasm - organic medium interface
interface_stats.cell_membrane_2 = 0;   % Cell 2 cytoplasm - organic medium interface
interface_stats.nucleus_membrane_1 = 0; % Nucleus 1 - cytoplasm 1 interface
interface_stats.nucleus_membrane_2 = 0; % Nucleus 2 - cytoplasm 2 interface
interface_stats.mitochondria_1 = 0;    % Mitochondria 1 - cytoplasm 1 interface
interface_stats.mitochondria_2 = 0;    % Mitochondria 2 - cytoplasm 2 interface
interface_stats.bulk = 0;              % Bulk volumes (no interface)

fprintf('\n\t . Tracking interface-aware R/C extraction:');
fprintf('\n\t\t - Electrode-Medium interface: Impedance spectroscopy domain (Warburg elements expected)');
fprintf('\n\t\t - Cell Membrane: Characteristic impedance platform (dispersive R/C)');
fprintf('\n\t\t - Nucleus Membrane: High-impedance domain (nuclear impedance ~1-100 MΩ)');
fprintf('\n\t\t - Mitochondrial Membrane: Organelle-level impedance');
fprintf('\n\t\t - Bulk Volumes: Tissue conductivity (R/C per mesh element)');

for i=1:1:size(fem_mesh_p,2)                                        % Loop on the nodes

        fprintf(fie, '%u\t%f\t%f\t%f\n', i, fem_mesh_p(1,i), fem_mesh_p(2,i), fem_mesh_p(3,i));     % Save the coordinates of the mesh in tlm.conf.Name.cor
    
        if size(tlm.result{i},2)~=0                                     % if the array for node i is filled in
            for j=7:7:size(tlm.result{i},2)
            
                if (tlm.result{i}{j}==0)                            % If we are not close to interfaces where special boundary conditions should be setup (excitation electrodes, membranes) on est en  plein dans une zone normale quoi

                    % ===== BULK VOLUME R/C COMPONENTS =====
                    % Standard mesh element conductivity (no interface effects)
                    interface_stats.bulk = interface_stats.bulk + 1;

                    % fprintf(fif, '%u\t%u\t%u\t%u\n', i, tlm.result{i}{j-6}, i ,tlm.result{i}{j-6});
                       
                        
                    if tlm.result{i}{j-4}~=-1
                        fprintf(fid, 'R%u_%u\t%u\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                        tlm.conf.Resistor=tlm.conf.Resistor+1;
                    end
                    if tlm.result{i}{j-3}~=0
                        fprintf(fid, 'C%u_%u\t%u\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                        tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                    end

                  
                elseif (tlm.result{i}{j}==1)    % The segment {i,j} is in the left or right outer electrodes
                    if (size(tlm.geom.boundaryEE{i},2)==1)   % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%ubis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%ubis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else                                % the node tlm.result{i}{j-6} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%ubis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%ubis\t%17.16e\n', i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==2)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the left or right outer electrodes
                    if (size(tlm.geom.boundaryEE{i},2)==1)           % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%uter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%uter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else                        % the node tlm.result{i}{j-6} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%uter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%uter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==3)    % The segment {i,j} is in the cytoplasm(1) and i or j is on the boundary with the organic medium
                    if (size(tlm.geom.boundaryEC{1,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%umbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%umbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else   % the node tlm.result{i}{j-7} is on the boundary               
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==4)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the cytoplasm(1)
                    if (size(tlm.geom.boundaryEC{1,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%umter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%umter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==5)    % The segment {i,j} is in the cytoplasm(1) and i or j is on the boundary with the nucleus(1)
                    if (size(tlm.geom.boundaryEN{1,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%unbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%unbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else    % the node tlm.result{i}{j-7} is on the boundary              
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==6)    % The segment {i,j} is in the nucleus(1) and i or j is on the boundary with the cytoplasme(1)
                    if (size(tlm.geom.boundaryEN{1,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%unter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%unter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==7)    % The segment {i,j} is in the cytoplasme(1) and i or j is on the boundary with the mitochondria(1)
                    if (size(tlm.geom.boundaryEM{1,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%uobis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%uobis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==8)    % The segment {i,j} is in the mitochondria(1) and i or j is on the boundary with the cytoplasme(1)
                    if (size(tlm.geom.boundaryEM{1,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%uoter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%uoter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==9)    % The segment {i,j} is in the cytoplasm(2) and i or j is on the boundary with the organic medium
                    if (size(tlm.geom.boundaryEC{2,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%umbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%umbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else   % the node tlm.result{i}{j-7} is on the boundary               
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==10)    % The segment {i,j} is in the organic medium and i or j is on the boundary with the cytoplasm(2)
                    if (size(tlm.geom.boundaryEC{2,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%umter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%umter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==11)    % The segment {i,j} is in the cytoplasm(2) and i or j is on the boundary with the nucleus(2)
                    if (size(tlm.geom.boundaryEN{2,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%unbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%unbis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else    % the node tlm.result{i}{j-7} is on the boundary              
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==12)    % The segment {i,j} is in the nucleus(2) and i or j is on the boundary with the cytoplasme(2)
                    if (size(tlm.geom.boundaryEN{2,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%unter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%unter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==13)    % The segment {i,j} is in the cytoplasme(2) and i or j is on the boundary with the mitochondria(2)
                    if (size(tlm.geom.boundaryEM{2,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%uobis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%uobis\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (tlm.result{i}{j}==14)    % The segment {i,j} is in the mitochondria(2) and i or j is on the boundary with the cytoplasme(2)
                    if (size(tlm.geom.boundaryEM{2,i},2)==1) % The node i is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%uoter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%uoter\t%u\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    else  % the node tlm.result{i}{j-7} is on the boundary
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'R%u_%u\t%u\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'C%u_%u\t%u\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                    end
                elseif (fem_mesh_t(5,i)==tlm.ind.dom.elec1)||...            % Here we are exactly on the special boundary (solicitation electrode)
                       (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.elec1)||...
                       (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.elec2)||...
                       (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.elec2)
                        % Impedance in the organic medium
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Rter%u_%u\t%uter\t%uter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Cter%u_%u\t%uter\t%uter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the solicitation electrode
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Rbis%u_%u\t%ubis\t%ubis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cbis%u_%u\t%ubis\t%ubis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                elseif ((fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Cytoplasme(1))&&...     % Here we are exactly on the special boundary (cell membrane)
                        (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.MilOrga))||...                 
                       ((fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Cytoplasme(1))&&...
                        (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.MilOrga))
                        % Impedance in the organic medium
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Rmter%u_%u\t%umter\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Cmter%u_%u\t%umter\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the Cytoplasme
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Rmbis%u_%u\t%umbis\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cmbis%u_%u\t%umbis\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                elseif ((fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Cytoplasme(2))&&...     % Here we are exactly on the special boundary (cell membrane)
                        (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.MilOrga))||...                 
                       ((fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Cytoplasme(2))&&...
                        (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.MilOrga))
                        % Impedance in the organic medium
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Rmter%u_%u\t%umter\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Cmter%u_%u\t%umter\t%umter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the Cytoplasme
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Rmbis%u_%u\t%umbis\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cmbis%u_%u\t%umbis\t%umbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                elseif ((fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Cytoplasme(1))&&...     % Here we are exactly on the special boundary (Nucleus membrane)
                        (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Nucleus(1)))||...                 
                       ((fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Cytoplasme(1))&&...
                        (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Nucleus(1)))    
                        % Impedance in the nucleus
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Rnter%u_%u\t%unter\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Cnter%u_%u\t%unter\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the Cytoplasme
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Rnbis%u_%u\t%unbis\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cnbis%u_%u\t%unbis\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                elseif ((fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Cytoplasme(2))&&...     % Here we are exactly on the special boundary (Nucleus membrane)
                        (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Nucleus(2)))||...                 
                       ((fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Cytoplasme(2))&&...
                        (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Nucleus(2)))    
                        % Impedance in the nucleus
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Rnter%u_%u\t%unter\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Cnter%u_%u\t%unter\t%unter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the Cytoplasme
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Rnbis%u_%u\t%unbis\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cnbis%u_%u\t%unbis\t%unbis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                elseif ((fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Cytoplasme(1))&&...     % Here we are exactly on the special boundary (Mitocho membrane)
                        (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Mitocho(1)))||...                 
                       ((fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Cytoplasme(1))&&...
                        (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Mitocho(1)))    
                        % Impedance in the mitochondria
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Roter%u_%u\t%uoter\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Coter%u_%u\t%uoter\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the Cytoplasme
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Robis%u_%u\t%uobis\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;  
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cobis%u_%u\t%uobis\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                elseif ((fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Cytoplasme(2))&&...     % Here we are exactly on the special boundary (Mitocho membrane)
                        (fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Mitocho(2)))||...                 
                       ((fem_mesh_t(5,tlm.result{i}{j-6})==tlm.ind.dom.Cytoplasme(2))&&...
                        (fem_mesh_t(5,tlm.result{i}{j-5})==tlm.ind.dom.Mitocho(2)))    
                        % Impedance in the mitochondria
                        if tlm.result{i}{j-4}~=-1
                            fprintf(fid, 'Roter%u_%u\t%uoter\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-4});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-3}~=0
                            fprintf(fid, 'Coter%u_%u\t%uoter\t%uoter\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-3});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                        % Impedance in the Cytoplasme
                        if tlm.result{i}{j-2}~=-1
                            fprintf(fid, 'Robis%u_%u\t%uobis\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-2});
                            tlm.conf.Resistor=tlm.conf.Resistor+1;
                        end
                        if tlm.result{i}{j-1}~=0
                            fprintf(fid, 'Cobis%u_%u\t%uobis\t%uobis\t%17.16e\n',i, tlm.result{i}{j-6}, i, tlm.result{i}{j-6}, tlm.result{i}{j-1});
                            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        end
                end %if (tlm.result{i}{j}==0)
            end %for j=7:7:size(tlm.result{i},2)
        end %if size(tlm.result{i},2)~=0
                            
        % Ajout des �l�ments parasites
        
        aire=0;
        
        if (size(tlm.geom.boundaryEE{i},1)==1) %parasite of the outer electrode
            % ===== INTERFACE 1: ELECTRODE-ORGANIC MEDIUM (SERUM) =====
            % This is the electrode-electrolyte interface
            % Expected behavior: Warburg impedance (frequency-dependent at low freq, resistive at high freq)
            interface_stats.electrode_medium = interface_stats.electrode_medium + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j)
                    %if the node is in this boundary triangle
                    % calcul de l'aire du triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Ci%u\t%ubis\t%uter\t%17.16e\n',i,i,i,tlm.var.Ci*aire);
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            fprintf(fid,'Rw%u\t%uquad\t%uter\tr=''%17.16e/sqrt(FREQ)''\n',i,i,i,tlm.var.Rwf/aire);
            tlm.conf.Resistor=tlm.conf.Resistor+1;            
            fprintf(fid,'Cw%u\t%uquad\t%uter\tc=''%17.16e*sqrt(FREQ)''\n',i,i,i,tlm.var.Cwf*aire);
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            fprintf(fid,'Rt%u\t%ubis\t%uquad\t%17.16e\n',i,i,i,tlm.var.Rt/aire);
            tlm.conf.Resistor=tlm.conf.Resistor+1;
        
        elseif (size(tlm.geom.boundaryEC{1,i},1)==1)               % cell membrane modele
            % ===== INTERFACE 2A: CELL 1 CYTOPLASM - ORGANIC MEDIUM (SERUM) =====
            % Cell 1 plasma membrane interface
            % Expected behavior: Characteristic impedance platform (Cole-Cole dispersion)
            interface_stats.cell_membrane_1 = interface_stats.cell_membrane_1 + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j) %if the node is in this boundary triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Rm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,((tlm.var.EpaisseurMembrane)/(tlm.var.sig.MembCel(1)*aire)));
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,((tlm.var.eps.MembCel(1)*aire)/tlm.var.EpaisseurMembrane));
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        
        elseif (size(tlm.geom.boundaryEC{2,i},1)==1)               % cell membrane modele
            % ===== INTERFACE 2B: CELL 2 CYTOPLASM - ORGANIC MEDIUM (SERUM) =====
            % Cell 2 plasma membrane interface  
            % Expected behavior: Characteristic impedance platform (Cole-Cole dispersion)
            interface_stats.cell_membrane_2 = interface_stats.cell_membrane_2 + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j) %if the node is in this boundary triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Rm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,((tlm.var.EpaisseurMembrane)/(tlm.var.sig.MembCel(2)*aire)));
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cm%u\t%umbis\t%umter\t%17.16e\n',i,i,i,((tlm.var.eps.MembCel(2)*aire)/tlm.var.EpaisseurMembrane));
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        
        elseif (size(tlm.geom.boundaryEN{1,i},1)==1)               % nucleus membrane modele
            % ===== INTERFACE 4A: NUCLEUS 1 - CYTOPLASM 1 =====
            % Nuclear envelope of nucleus 1
            % Expected behavior: High-frequency impedance ~1-100 MΩ (nuclear pore complex effects)
            interface_stats.nucleus_membrane_1 = interface_stats.nucleus_membrane_1 + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j) %if the node is in this boundary triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Rn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurNucleus/(tlm.var.sig.MembNuc(1)*aire)));
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,((tlm.var.eps.MembNuc(1)*aire)/tlm.var.EpaisseurNucleus));
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        
        elseif (size(tlm.geom.boundaryEN{2,i},1)==1)               % nucleus membrane modele
            % ===== INTERFACE 4B: NUCLEUS 2 - CYTOPLASM 2 =====
            % Nuclear envelope of nucleus 2
            % Expected behavior: High-frequency impedance ~1-100 MΩ (nuclear pore complex effects)
            interface_stats.nucleus_membrane_2 = interface_stats.nucleus_membrane_2 + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j) %if the node is in this boundary triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Rn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurNucleus/(tlm.var.sig.MembNuc(2)*aire)));
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Cn%u\t%unbis\t%unter\t%17.16e\n',i,i,i,((tlm.var.eps.MembNuc(2)*aire)/tlm.var.EpaisseurNucleus));
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        
        elseif (size(tlm.geom.boundaryEM{1,i},1)==1)               % Mitochondria membrane modele
            % ===== INTERFACE 5A: MITOCHONDRIA 1 - CYTOPLASM 1 =====
            % Outer mitochondrial membrane of mitochondria 1
            % Expected behavior: Intermediate impedance (10k-1M Ω), lower than nuclear membrane
            interface_stats.mitochondria_1 = interface_stats.mitochondria_1 + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j) %if the node is in this boundary triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Ro%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurMitochon/(tlm.var.sig.MembMit(1)*aire)));
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Co%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,((tlm.var.eps.MembMit(1)*aire)/tlm.var.EpaisseurMitochon));
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
                        
        elseif (size(tlm.geom.boundaryEM{2,i},1)==1)               % Mitochondria membrane modele
            % ===== INTERFACE 5B: MITOCHONDRIA 2 - CYTOPLASM 2 =====
            % Outer mitochondrial membrane of mitochondria 2
            % Expected behavior: Intermediate impedance (10k-1M Ω), lower than nuclear membrane
            interface_stats.mitochondria_2 = interface_stats.mitochondria_2 + 1;
            for j=1:1:size(fem_mesh_e,2) %loop on the triangles at interface
                if i==fem_mesh_e(1,j)||i==fem_mesh_e(2,j)||i==fem_mesh_e(3,j) %if the node is in this boundary triangle
                    d12=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(2,j))).^2)^0.5;
                    d23=sum((fem_mesh_p(:,fem_mesh_e(2,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    d13=sum((fem_mesh_p(:,fem_mesh_e(1,j))-fem_mesh_p(:,fem_mesh_e(3,j))).^2)^0.5;
                    s=0.5*(d12+d23+d13);
                    aire=aire+((s*(s-d12)*(s-d13)*(s-d23))^0.5)/3;
                end  
            end
            
            fprintf(fid,'Ro%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,(tlm.var.EpaisseurMitochon/(tlm.var.sig.MembMit(2)*aire)));
            tlm.conf.Resistor=tlm.conf.Resistor+1;
            fprintf(fid,'Co%u\t%uobis\t%uoter\t%17.16e\n',i,i,i,((tlm.var.eps.MembMit(2)*aire)/tlm.var.EpaisseurMitochon));
            tlm.conf.Capacitor=tlm.conf.Capacitor+1;
            
        end  
        
end %for i

% ===== CRITICAL FIX: Bridge electrodes to circuit measurement nodes =====
% Issue: Electrode nodes were isolated from circuit
% causing Xyce warnings about floating nodes and no DC path to ground
% Solution: Connect electrodes to mesh measurement points using dynamic nodes

fprintf('\n\t . Adding electrode bridges for circuit connectivity:');

% Bridge 1: Connect excitation source (Vin) to nearest connected mesh node
% Using very high resistance to minimize impedance impact
bridge_r_in = 1.0e10;  % 10 GΩ - high enough to not affect measurement
fprintf(fid, 'Rbridge_in\t%u\t%u\t%17.16e\n', tlm.ind.pt.elec2, mesu1, bridge_r_in);
fprintf(fid, 'Cbridge_in\t%u\t%u\t%17.16e\n', tlm.ind.pt.elec2, mesu1, 1.0e-21);  % negligible capacitance
tlm.conf.Resistor = tlm.conf.Resistor + 1;
tlm.conf.Capacitor = tlm.conf.Capacitor + 1;

fprintf('\n\t\t - Bridge 1 (excitation): Node %u ↔ Node %u, R=%.2e Ω', tlm.ind.pt.elec2, mesu1, bridge_r_in);

% Bridge 2: Connect source impedance to nearest connected mesh node
% Completes the current path: Vin → Rg → circuit → mesu2 → back through mesh
fprintf(fid, 'Rbridge_out\t%u\t%u\t%17.16e\n', tlm.ind.pt.elec1, mesu2, bridge_r_in);
fprintf(fid, 'Cbridge_out\t%u\t%u\t%17.16e\n', tlm.ind.pt.elec1, mesu2, 1.0e-21);
tlm.conf.Resistor = tlm.conf.Resistor + 1;
tlm.conf.Capacitor = tlm.conf.Capacitor + 1;

fprintf('\n\t\t - Bridge 2 (return): Node %u ↔ Node %u, R=%.2e Ω', tlm.ind.pt.elec1, mesu2, bridge_r_in);
fprintf('\n\t\t - Bridge connections added: 2 R + 2 C pairs');

fprintf(fid, '.END\n');

% Modified by: Tina - Generate comprehensive netlist generation summary
% This provides critical statistics for validating circuit extraction quality
fprintf('\n\t . Netlist Generation Summary (WITH BRIDGE CONNECTIONS):');
fprintf('\n\t\t - Total nodes in mesh: %d', size(fem_mesh_p, 2));
fprintf('\n\t\t - Extracted resistors: %d (includes 2 bridge connections)', tlm.conf.Resistor);
fprintf('\n\t\t - Extracted capacitors: %d (includes 2 bridge connections)', tlm.conf.Capacitor);
fprintf('\n\t\t - Resistors + Capacitors: %d (%.1f elements per node)', ...
        tlm.conf.Resistor + tlm.conf.Capacitor, ...
        (tlm.conf.Resistor + tlm.conf.Capacitor) / size(fem_mesh_p, 2));

% Modified by: Tina - Validate element counts are reasonable
% If counts are too low, most nodes are isolated (bad)
% If counts are very high, may indicate mesh issues or over-extraction
if (tlm.conf.Resistor + tlm.conf.Capacitor) < size(fem_mesh_p, 2)
    fprintf('\n\t\t . Warning: element count (%d) < node count (%d)', ...
        tlm.conf.Resistor + tlm.conf.Capacitor, size(fem_mesh_p, 2));
    fprintf('\n\t\t   This suggests many isolated nodes.');
end

% Modified by: Tina - Log netlist file paths for reference
fprintf('\n\t . Output files generated:');
fprintf('\n\t\t - Netlist: %s', sprintf('%s.cir', tlm.conf.Name));
fprintf('\n\t\t - Coordinates: %s', sprintf('%s.cor', tlm.conf.Name));

% Modified by: Tina - Store extraction statistics in tlm structure
% These can be used for later validation and debugging
tlm.extraction.num_resistors = tlm.conf.Resistor;
tlm.extraction.num_capacitors = tlm.conf.Capacitor;
tlm.extraction.num_nodes_total = size(fem_mesh_p, 2);
tlm.extraction.extraction_density = (tlm.conf.Resistor + tlm.conf.Capacitor) / size(fem_mesh_p, 2);
tlm.extraction.bridges_added = 2;  % Track that bridges were added for connectivity

fprintf('\n\t\t - Bridge 2 (return): Node %u ↔ Node %u, R=%.2e Ω', tlm.ind.pt.elec1, mesu2, bridge_r_in);
fprintf('\n\t\t - Bridge connections added: 2 R + 2 C pairs');

% ===== INTERFACE-AWARE R/C EXTRACTION SUMMARY =====
% Report on which cellular interfaces contributed to the circuit
fprintf('\n\t . Interface-Aware R/C Extraction Report:');
fprintf('\n\t\t - Electrode-Medium Interface (Warburg impedance): %d nodes', interface_stats.electrode_medium);
fprintf('\n\t\t - Cell 1 Membrane (plasma membrane): %d nodes', interface_stats.cell_membrane_1);
fprintf('\n\t\t - Cell 2 Membrane (plasma membrane): %d nodes', interface_stats.cell_membrane_2);
fprintf('\n\t\t - Nucleus 1 Membrane (nuclear envelope): %d nodes', interface_stats.nucleus_membrane_1);
fprintf('\n\t\t - Nucleus 2 Membrane (nuclear envelope): %d nodes', interface_stats.nucleus_membrane_2);
fprintf('\n\t\t - Mitochondria 1 Membrane: %d nodes', interface_stats.mitochondria_1);
fprintf('\n\t\t - Mitochondria 2 Membrane: %d nodes', interface_stats.mitochondria_2);
fprintf('\n\t\t - Bulk Volume (no interfaces): %d elements', interface_stats.bulk);

% Calculate and report interface coverage
total_interface_nodes = interface_stats.electrode_medium + interface_stats.cell_membrane_1 + ...
                       interface_stats.cell_membrane_2 + interface_stats.nucleus_membrane_1 + ...
                       interface_stats.nucleus_membrane_2 + interface_stats.mitochondria_1 + ...
                       interface_stats.mitochondria_2;

fprintf('\n\t . Interface Coverage Analysis:');
fprintf('\n\t\t - Total nodes with interfaces: %d (%.1f%% of mesh)', total_interface_nodes, ...
        100 * total_interface_nodes / size(fem_mesh_p, 2));
fprintf('\n\t\t - Bulk components: %d (%.1f%% of mesh)', interface_stats.bulk, ...
        100 * interface_stats.bulk / size(fem_mesh_p, 2));
fprintf('\n\t\t - Cellular interfaces detected: %d types with nodes', ...
        max(1, min(1, interface_stats.cell_membrane_1)) + max(1, min(1, interface_stats.cell_membrane_2)) + ...
        max(1, min(1, interface_stats.nucleus_membrane_1)) + max(1, min(1, interface_stats.nucleus_membrane_2)) + ...
        max(1, min(1, interface_stats.mitochondria_1)) + max(1, min(1, interface_stats.mitochondria_2)));

% Store interface statistics for validation
tlm.extraction.interface_stats = interface_stats;
tlm.extraction.total_interface_nodes = total_interface_nodes;
tlm.extraction.interface_coverage_percent = 100 * total_interface_nodes / size(fem_mesh_p, 2);

% ===== FREQUENCY-SPECIFIC ANALYSES FOR PER-NODE VOLTAGE OUTPUT =====
% Generate .spi_cou files for each frequency point containing all node voltages
% This is required by Read3D.m for 3D potential mapping and FEM field reconstruction

fprintf('\n\t . Generating frequency-specific AC analyses for node voltage output (.spi_cou files):');

% Generate AC analyses at min, intermediate, and max frequencies
% Each analysis outputs all node voltages to a frequency-labeled file
% Using same filename format as Read3D.m: tlm.conf.Name_FREQUENCYHz.spi_cou
freq_points = [tlm.var.frequence.min, tlm.var.frequence.int, tlm.var.frequence.max];
freq_labels = {'minimum', 'intermediate', 'maximum'};

for freq_idx = 1:length(freq_points)
    freq_val = freq_points(freq_idx);
    freq_label = freq_labels{freq_idx};
    
    % Create filename matching Read3D.m format: strcat(tlm.conf.Name, "_", num2str(f), "Hz.spi_cou")
    % Example: Simul15-Apr-2026_15-35-37_1000Hz.spi_cou
    spi_cou_filename = sprintf('%s_%s', tlm.conf.Name, sprintf('%gHz', freq_val));
    
    % Write .CONTROL block with frequency-specific analysis
    % Format: AC DEC points_start freq_start freq_stop (DEC = decade, 1 = single point analysis)
    fprintf(fid, '.CONTROL\n');
    fprintf(fid, '  DESTROY ALL\n');  % Clear previous simulation results
    fprintf(fid, '  AC DEC 1 %g %g\n', freq_val, freq_val);  % Single-point AC analysis at freq_val
    fprintf(fid, '  WRITE %s.spi_cou all\n', spi_cou_filename);  % Output all node voltages to file
    fprintf(fid, '.ENDC\n');
    
    fprintf('\n\t\t - %s frequency (%.2e Hz): output → %s.spi_cou', freq_label, freq_val, spi_cou_filename);
end

fprintf(fid, '.END\n');

fclose(fid);

fclose(fie);

end

function [node_out, moved] = nearest_connected_node(node_in, mesh_p, connected_mask)
    node_out = node_in;
    moved = false;

    if isempty(node_in) || node_in < 1 || node_in > size(mesh_p,2)
        return;
    end

    if node_in <= numel(connected_mask) && connected_mask(node_in)
        return;
    end

    candidates = find(connected_mask);
    if isempty(candidates)
        return;
    end

    target = mesh_p(:, node_in);
    deltas = mesh_p(:, candidates) - target;
    d2 = sum(deltas.^2, 1);
    [~, imin] = min(d2);
    node_out = candidates(imin);
    moved = (node_out ~= node_in);
end

function connected_mask = build_spice_node_mask(tlm, mesh_p)
    connected_mask = false(1, size(mesh_p, 2));

    if ~iscell(tlm.result)
        return;
    end

    nNodes = min(numel(tlm.result), size(mesh_p, 2));
    for i = 1:nNodes
        node_result = tlm.result{i};
        if isempty(node_result)
            continue;
        end

        is_outer_boundary_node = false;
        if isfield(tlm, 'geom') && isfield(tlm.geom, 'boundaryEE') && i <= numel(tlm.geom.boundaryEE)
            is_outer_boundary_node = ~isempty(tlm.geom.boundaryEE{i});
        end

        for j = 7:7:numel(node_result)
            if isempty(node_result{j})
                continue;
            end

            if j-6 < 1 || j-4 < 1 || j-3 < 1
                continue;
            end

            target_node = node_result{j-6};
            resistor_value = node_result{j-4};
            capacitor_value = node_result{j-3};

            if isempty(target_node) || target_node < 1 || target_node > size(mesh_p, 2)
                continue;
            end

            if resistor_value ~= -1 || capacitor_value ~= 0
                if is_outer_boundary_node
                    connected_mask(i) = true;
                end
                if isfield(tlm, 'geom') && isfield(tlm.geom, 'boundaryEE') && target_node <= numel(tlm.geom.boundaryEE) && ~isempty(tlm.geom.boundaryEE{target_node})
                    connected_mask(target_node) = true;
                end
            end
        end
    end
end