%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 2.0
%
%   Authors: Tina
%   
%   Date: March 2026
%   Modified by: Tina - NEW FILE for XYCE output parsing
%
%   Function: Parse Xyce CSV output and extract node voltages
%
%   Purpose: This function parses the .cir.FD.csv file generated by Xyce
%            to extract per-node voltage data for each frequency point.
%            This ensures complete verification of the electromagnetic
%            field distribution and node connectivity in the circuit.
%
%   Called by: SolFEM3D.m
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [xyce_nodes] = parseXyceOutput(csv_filename, tlm)

% Modified by: Tina - Parse XYCE CSV output file to extract node information
% This enables per-node voltage verification and connectivity checking

fprintf('\n\t\t . Parsing XYCE output file: %s', csv_filename);

% Check if file exists
if ~exist(csv_filename, 'file')
    fprintf('\n\t\t . Warning: XYCE output file not found: %s', csv_filename);
    xyce_nodes = [];
    return;
end

% Modified by: Tina - Read raw CSV data from XYCE
% Store both header and data for complete analysis
try
    raw_data = readcell(csv_filename);  % Read as cell array to handle headers
    fprintf('\n\t\t . File read successfully');
catch ME
    fprintf('\n\t\t . Error reading XYCE file: %s', ME.message);
    xyce_nodes = [];
    return;
end

% Modified by: Tina - Extract header row to identify node voltage columns
% Xyce CSV format: Index, FREQ, V(node1), V(node2), ...
if size(raw_data, 1) < 2
    fprintf('\n\t\t . Error: XYCE file has insufficient data');
    xyce_nodes = [];
    return;
end

header = raw_data(1, :);
fprintf('\n\t\t . Header columns found: %d', length(header));

% Modified by: Tina - Parse column headers to identify node indices
% Extract node IDs from column names like 'V(174)' or 'V(1,174)'
xyce_nodes.columns = {};
xyce_nodes.node_ids = [];
xyce_nodes.voltage_data = [];

for col_idx = 1:length(header)
    header_str = char(header{col_idx});
    
    % Modified by: Tina - Check if column header contains voltage notation V(...)
    if contains(header_str, 'V(')
        % Extract node ID from V(node) format
        % Handle both V(n) and V(n1,n2) format
        start_idx = strfind(header_str, 'V(') + 2;
        end_idx = strfind(header_str, ')') - 1;
        
        if ~isempty(start_idx) && ~isempty(end_idx)
            node_str = header_str(start_idx:end_idx);
            
            % Modified by: Tina - Parse node ID (may be single node or differential)
            % For single node: V(174) → node_id = 174
            % For differential: V(174,175) → primary_node = 174
            if contains(node_str, ',')
                parts = strsplit(node_str, ',');
                node_id = str2double(parts{1});
            else
                node_id = str2double(node_str);
            end
            
            if ~isnan(node_id)
                xyce_nodes.columns = [xyce_nodes.columns; header_str];
                xyce_nodes.node_ids = [xyce_nodes.node_ids; node_id];
            end
        end
    end
end

% Modified by: Tina - Extract numerical data from XYCE CSV
% Skip first row (header) and extract voltage columns
try
    numerical_data = cell2mat(raw_data(2:end, :));
    xyce_nodes.frequency = numerical_data(:, 1);
    
    % Modified by: Tina - Extract voltage data for each node column
    % Voltage columns start after frequency and impedance columns
    voltage_col_indices = find(~isnan(xyce_nodes.node_ids));
    
    if ~isempty(voltage_col_indices)
        xyce_nodes.voltage_data = numerical_data(:, voltage_col_indices + 1);
        fprintf('\n\t\t . Node voltages extracted:');
        fprintf('\n\t\t   - Frequencies: %d points', length(xyce_nodes.frequency));
        fprintf('\n\t\t   - Voltage columns: %d nodes', length(xyce_nodes.node_ids));
        fprintf('\n\t\t   - Node IDs: %s', mat2str(xyce_nodes.node_ids(1:min(5,end))));
    else
        fprintf('\n\t\t . Warning: No voltage columns found in XYCE output');
    end
    
catch ME
    fprintf('\n\t\t . Error extracting numerical data: %s', ME.message);
    xyce_nodes = [];
    return;
end

% Modified by: Tina - Validate extracted data dimensions
% Ensure voltage data matches frequency points
if size(xyce_nodes.voltage_data, 1) ~= length(xyce_nodes.frequency)
    fprintf('\n\t\t . Warning: Voltage data rows (%d) do not match frequencies (%d)', ...
        size(xyce_nodes.voltage_data, 1), length(xyce_nodes.frequency));
end

fprintf('\n\t\t . XYCE output parsing complete');

end
