%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                              BIOCAD Program
%                               Release 1.0
%
%   Authors: Vincent Senez
%   
%   Release 1.0 : January 2019
%   Refactored  : March 2026
%
%   Function : Solve the 3D system by FEM Method
%
%   Called by: Compute.m
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [tlm,model]=SolFEM3D(tlm,model)

%Initialization
tlm.sol.fre=[];
tlm.sol.val = []; % Vide les anciens résultats de Bode/Impédance
tlm.sol.num = []; % Vide les anciens potentiels électriques
tlm.var.X   = []; % Vide les anciennes coordonnées X
tlm.var.Y   = []; % Vide les anciennes coordonnées Y
tlm.var.Z   = []; % Vide les anciennes coordonnées Z

tlm.conf.Name0=tlm.conf.Name;
name1=sprintf('%s.spi',tlm.conf.Name0);     % Name of the file
fid=fopen(name1, 'r');                     % Open the File
xyceCsvName=sprintf('%s.cir.FD.csv',tlm.conf.Name0);

% Read the SPI file generated by the TLM solver to extract the frequencies
if fid>=0       % The file exists
    
    tlineref='Values:';

    i=0;

    while ~feof(fid)
        tlineread = fgetl(fid);
        C = strcmp(tlineref,tlineread);
        if C==1
            imul=log10(tlm.var.frequence.max)-log10(tlm.var.frequence.min);
            while i<(tlm.var.frequence.step*imul+1)
                    tlineread = fgetl(fid);
                    tlm.sol.fre(i+1,:)=str2num(tlineread);
                    tlineread = fgetl(fid);
                    tlineread = fgetl(fid);
                    tlineread = fgetl(fid);
                    i=i+1;
            end
            break
        end
    end

    fclose(fid);

else
    if exist(xyceCsvName,'file')==2
        xyceData=readmatrix(xyceCsvName);
        if ~isempty(xyceData) && size(xyceData,2)>=2
            tlm.sol.fre(:,1)=xyceData(:,1);
            tlm.sol.fre(:,2)=xyceData(:,2);
            fprintf('\n\t\t . The Xyce CSV file has been exploited to extract frequencies');
        else
            fprintf('\n\t\t . The Xyce CSV file exists but is malformed');
        end
    else
        fprintf('\n\t\t . The SPI File does not exist in the current result directory');
    end

end

if isempty(tlm.sol.fre) || size(tlm.sol.fre,2)<2
    error('No valid frequency list found for FEM study. Expected %s.spi or %s', tlm.conf.Name0, xyceCsvName);
end

% Set the parameters in COMSOL based on the variables in BIOCAD
%model.param.set('sig_elec', num2str(tlm.var.sig.electrode));
%model.param.set('eps_elec', num2str(tlm.var.eps.electrode/tlm.var.eps0));
%model.param.set('sig_med', num2str(tlm.var.sig.MilOrga));
%model.param.set('eps_med', num2str(tlm.var.eps.MilOrga/tlm.var.eps0));
%model.param.set('v_in', num2str(tlm.var.v0));

% --- PREPARATION DES FREQUENCES ET RESOLUTION ---

% We add the frequencies from the SPI file to the COMSOL study.
freq_str = sprintf('%g ', tlm.sol.fre(:,2)); 
model.study(tlm.conf.study_label).feature('freq').set('plist', freq_str);
model.study(tlm.conf.study_label).feature('freq').set('preusesol', 'no');

% Run the COMSOL study to compute the solution at the specified frequencies.
model.study(tlm.conf.study_label).run;
data = mpheval(model,'V');

% Extract the impedance Z
Y_complex = mphglobal(model, tlm.conf.admitance); % Admittance Y = 1/Z
Z_complex = 1 ./ Y_complex;
Z_complex = Z_complex(:); 

% Prepare the results for the .fem file
freqs = tlm.sol.fre(:,2);
tlm.sol.val(:,1) = freqs;
tlm.sol.val(:,2) = 20 * log10(abs(Z_complex));
tlm.sol.val(:,3) = angle(Z_complex) * 180 / pi;
tlm.sol.val(:,7) = real(Z_complex);
tlm.sol.val(:,8) = imag(Z_complex);


% Extract the coordinates of the nodes 
tlm.var.X(:,1) = data.p(1,:)' * tlm.var.scale;
tlm.var.Y(:,1) = data.p(2,:)' * tlm.var.scale;
tlm.var.Z(:,1) = data.p(3,:)' * tlm.var.scale;

nFreq=size(tlm.sol.fre,1);
for a=1:1:nFreq
       
    f=tlm.sol.fre(a,2);

    if (abs(f-tlm.var.frequence.min)<2e-10 || ...
        abs(f-tlm.var.frequence.int)<2e-10 || ...
        abs(f-tlm.var.frequence.max)<2e-10)
        
       tlm.conf.Name=strcat(tlm.conf.Name0,'_',num2str(f),'Hz'); 

       tlm.sol.num(:,1) = abs(data.d1(a,:))';
            
       % Save the results of the simulation in a file xx.fem_cou

       name1=sprintf('%s.fem_cou',tlm.conf.Name);        % Name of the file for the Net List
       fid=fopen(name1, 'w');                            % Open the File

       fprintf(fid, '%s.fem_cou\n',tlm.conf.Name);       % Write the first line of the file which is use as a title of the graphical output
       fprintf(fid, '********************************************************************************\n');            
       fprintf(fid, '*\n');            
       fprintf(fid, '*            3D Map of Electric Potential Calculated by FEM \n'); 
       fprintf(fid, '*                THE FREQUENCY FOR THIS RESULT IS %e HERTZ \n',f); 
       fprintf(fid, '*\n');            
       fprintf(fid, '*                              BIOCAD Program\n');            
       fprintf(fid, '*                               Release 1.0\n');            
       fprintf(fid, '*\n');            
       fprintf(fid, '*   Authors: Vincent Senez\n'); 
       fprintf(fid, '*\n');            
       fprintf(fid, '*   Release 1.0 : January 2019\n');     
       fprintf(fid, '*\n');            
       fprintf(fid, '********************************************************************************\n');            

       % Write the data in the file
       matrice_ecriture = [tlm.var.X(:,1), tlm.var.Y(:,1), tlm.var.Z(:,1), tlm.sol.num(:,1)]';
       fprintf(fid, '%g %g %g %g\n', matrice_ecriture);
         
       fclose(fid);
        
    end         
end

% Save the results of the simulation in a file xx.fem

name1=sprintf('%s.fem',tlm.conf.Name0);        % Name of the file for the Net List
fid=fopen(name1, 'w');                         % Open the File

fprintf(fid, '%s.fem\n',tlm.conf.Name0);       % Write the first line of the file which is use as a title of the graphical output
fprintf(fid, '********************************************************************************\n');            
fprintf(fid, '*\n');            
fprintf(fid, '*                        Bode Diagram Calculated by FEM \n'); 
fprintf(fid, '*\n');            
fprintf(fid, '*                              BIOCAD Program\n');            
fprintf(fid, '*                               Release 1.0\n');            
fprintf(fid, '*\n');            
fprintf(fid, '*   Authors: Vincent Senez \n'); 
fprintf(fid, '*\n');            
fprintf(fid, '*   Release 1.0 : January 2019\n');          
fprintf(fid, '*\n');            
fprintf(fid, '********************************************************************************\n');            
fprintf(fid, '*\n');            
fprintf(fid, '* Values:\n');            

% Write the data in the file
fprintf(fid, '%1.3g %1.10g %1.10g %1.10g %1.10g\n', tlm.sol.val(:,[1, 2, 3, 7, 8])');

fclose(fid);

tlm.conf.Name=tlm.conf.Name0;